ChartsOrg/Charts

Charts.podspec

I've added a podspec since I will be using this with cocoapods. I have not pushed it to the repo that manages pods just yet since the current specification is not complete. Cocoapods requires that a version be tagged in order to work properly and be able to distinguish between versions. I have done this in my own fork and used my fork as the source for the pod but I'd like it to point to the original source.
Once you tag a version, I will update this line: `s.source = { :git => "https://github.com/petester42/ios-charts.git", :tag => "0.0.1" }` to point to here and then you can merge.
I also tried making sure carthage support works but the way the current project is setup makes it so that the schemes are not there when running carthage.

Added a podspec

---

Charts/Charts.xcodeproj/xcshareddata/xcschemes/Charts.xcscheme

Added Charts.framework shared scheme for Carthage support.

Shared Charts.framework scheme

---

Charts/Classes/Components/ChartXAxis.swift

Importing this class into an iOS 7 project raised an error for unresolved
identifier `CGFloat`.
This pull request fixes [the bug](https://github.com/danielgindi/ios-charts/issues/19).

Add missing UIKit

---

Charts/Classes/Data/PieChartData.swift

Hey!
We're trying to use your great library from Swift and while we're copying your sample code, we're running into problems because init methods are not inherited in Swift. Since your sample code uses ObjC, maybe that's why it works on ObjC but it doesn't in Swift
You can use this Swift code [https://gist.github.com/jmnavarro/659d29cb3434a0854ae8] (copied from PieCharViewController from your sample) to see why it's necessary
Thanks!

Add 'init' to PieChartData to be used from Swift

---

Charts/Classes/Renderers/ChartXAxisRenderer.swift
ChartsDemo/Classes/Demos/LineChart1ViewController.m

Bottom position of limit line on x-axis was incorrectly set to y coordinate instead of x.
Current:
Fixed:

Fix x-axis limit line render issue.

---

Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Data/CandleChartDataSet.swift
Charts/Classes/Data/ChartData.swift
Charts/Classes/Data/ChartDataSet.swift
Charts/Classes/Data/CombinedChartData.swift

This adds the auto scaling we've talked about in #89 . There is an issue that I haven't been able to solve yet, though. Sometimes during panning, the chart is kind of stuck in a re-drawing cycle which. I've got no idea why this is happening, but maybe you've got an idea, so please don't merge this as it is.
With autoscaling enabled, the drawRect method runs about 10% slower for the datasets of the ChartsDemo application. In our finance chart with 250 candles, this slow down isn't noticeable on an actual device.

AutoScaling yAxis during panning / zooming

---

Charts/Classes/Charts/BarLineChartViewBase.swift

As I said in issue #92 the x axis offset doesn't adjust when you disable x axis labels. With this change you can have the x grid without labels but the chart area still fills the entire viewport.

Offset adjustment when drawLabels on the x axis is disabled.

---

Charts/Classes/Charts/PieRadarChartViewBase.swift
Charts/Classes/Data/ChartDataSet.swift
Charts/Classes/Renderers/ChartYAxisRendererRadarChart.swift
Charts/Classes/Renderers/RadarChartRenderer.swift

The background is that not every data in every dataSet is valid number in real life.
add NaN check to allow non-digits handleing. if a CGPoint contains NaN, simply ignore it, this will ignore current point and continue the path with next valid point.
This is helpful, where dataSet 1 contains invalid data but dataSet 2 has valid data. People can have a chance to insert NaN if user found the data is nil/null/NSNotFound/ifinity/DOUBLE_MAX.... any number that cannot be drawn on screen or even exists in real life, and still get the chart.
for example, 
xValues: [1,2,3,4,5]
dataSet 1: [5,6,NaN,8,9]
dataSet 2: [11,12,13,14,15]
With NaN support, the radar chart will connect dataSet 1 values: 5-6-8-9 as a web, and dataSet 2 as 11-12-13-14-15 as another web.
**Attention:**
I only add the code for …

add NaN check to allow non-digits handling for radar chart

---

Charts/Classes/Renderers/ChartYAxisRendererRadarChart.swift

My bad, made a terrible mistake. the purpose is to check if first is -0.0, turn it into 0.0. I forgot to copy it from my project...

Fix a silly bug. should check if first is -0.0

---

Charts/Classes/Charts/BarLineChartViewBase.swift

I would like to display several sequential data sets on the same line chart (two data sets are sequential if the last element of the 1st set is also the first element of the 2nd one e.g. [1,2,3] and [3,4,5]); unfortunately, set up so, the line chart stops properly display balloon markers (they appear only over some points of the plot). The attached commit fixes the described issue.

The line charts have started to properly display balloon markers

---

Charts/Classes/Data/CandleChartDataSet.swift
Charts/Classes/Renderers/CandleStickChartRenderer.swift
ChartsDemo/Classes/Demos/CandleStickChartViewController.m

Candle chart - make the shadow same color as an increasing/decreasing candle color #122

Candle chart - make the shadow same color as an candle color #122

---

Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Charts/ChartViewBase.swift
Charts/Classes/Charts/PieChartView.swift
Charts/Classes/Charts/PieRadarChartViewBase.swift
Charts/Classes/Charts/RadarChartView.swift

- Failable initializers can’t override non-failable initializers
- observeValueForKeyPath’s signature didn’t match the signature of the
method it was overriding

Fixes to allow the code to compile with Swift 2.0

---

Charts/Classes/Charts/BarChartView.swift
Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Renderers/BarChartRenderer.swift
Charts/Classes/Renderers/HorizontalBarChartRenderer.swift
Charts/Classes/Utils/ChartTransformer.swift

Alright, I managed to squash commits and merge v2.1.2 and #221. I will paste old message from #221 below.
Try to fix wrong position bug. use entry.xIndex instead of j of dataSet.entryCount to calculate the offset and position. Issue #214 + #242
The idea is, because not every xIndex will have a dataEntry, if the data is invalid (nil/nan/null), the entryCount will be less than xValsCount.
For example, xVals: [0,1,2,3,4,5,6,7,8,9,10], if there are two dataSets, like below:
xIndex:0 value:100, xIndex:10 value:200
xIndex:0 value:1000, xIndex:10 value:2000
Current logic will use entryCount instead of xValsCount to calculate the matrix and position, which will lead to shorter xPosition value on xAxis. issue #214 has the screenshot.
What I changed is I always use xValsCount and actual xIndex …

try to fix bar chart + Horizontal Bar chart wrong render + highlight position bug for issue #214 and #242.

---

Charts/Charts.xcodeproj/project.pbxproj
Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Charts/ChartViewBase.swift
Charts/Classes/Components/ChartMarker.swift
Charts/Classes/Data/ChartDataEntry.swift
Charts/Classes/Data/ChartDataSet.swift
Charts/Classes/Renderers/BarChartRenderer.swift
Charts/Classes/Renderers/BubbleChartRenderer.swift
Charts/Classes/Renderers/CandleStickChartRenderer.swift
Charts/Classes/Renderers/ChartAxisRendererBase.swift
Charts/Classes/Renderers/ChartDataRendererBase.swift
Charts/Classes/Renderers/ChartLegendRenderer.swift
Charts/Classes/Renderers/ChartXAxisRenderer.swift
Charts/Classes/Renderers/ChartXAxisRendererBarChart.swift
Charts/Classes/Renderers/ChartXAxisRendererHorizontalBarChart.swift
Charts/Classes/Renderers/ChartXAxisRendererRadarChart.swift
Charts/Classes/Renderers/ChartYAxisRenderer.swift
Charts/Classes/Renderers/ChartYAxisRendererHorizontalBarChart.swift
Charts/Classes/Renderers/ChartYAxisRendererRadarChart.swift
Charts/Classes/Renderers/CombinedChartRenderer.swift
Charts/Classes/Renderers/HorizontalBarChartRenderer.swift
Charts/Classes/Renderers/LineChartRenderer.swift
Charts/Classes/Renderers/LineScatterCandleRadarChartRenderer.swift
Charts/Classes/Renderers/PieChartRenderer.swift
Charts/Classes/Renderers/RadarChartRenderer.swift
Charts/Classes/Renderers/ScatterChartRenderer.swift
Charts/Classes/Utils/CALayer+Extensions.swift
Charts/Classes/Utils/ChartUtils.swift
Charts/Classes/Utils/UIGraphics+Extensions.swift
ChartsDemo/Classes/Components/BalloonMarker.swift

I know its a lot of changes but this beta made the `UIGraphicsGetCurrentContext()` now return an optional value. So instead of adding `if let` or `guard` everywhere I decided to refactor the methods that took `CGContext` to `CGContext?` and add extensions to methods that didn't take optional values. Hopefully apple moves the 2 methods that I extended to take in optional values as well so the extensions can be removed. (fixes #287)

Fixes xcode beta 5 compile errors

---

Charts/Classes/Charts/BarLineChartViewBase.swift

1. change all gestures and their handlers to internal
2. use import UIKit instead of UIKit.UIGestureRecognizer

Minor refactor for BarLineChartViewBase

---

Charts/Classes/Renderers/ChartYAxisRendererRadarChart.swift

For issue #166
we have to check if Double(yMin) / interval will be -1<x<0, if this is the case, ceil(x) would be 0. but I think we need it to be -1.
negative values using ceil is not correct, I think. This will lead the minimum value is larger than the data values, like if I have -0.5 , 1 , it calculate as [0,1], not [-1,1]. (ceil(-0.5) = 0)
In order to render the negative values correctly,
_yAxis.axisMinimum = _yAxis.entries[0];
is the key.
I have been thinking about different ways to fix. But I was suddenly realized the whole reason is the axisMinimum is not changed while the entries have been modified. Add this line solved my problem, and other radar charts remain good on my side. So I think this should be the correct way to fix it.
@danielgindi you must double check here, because I am …

fix radar chart negative value rendering bug if startAtZeroEnabled is false for issue #166

---

Charts/Charts.xcodeproj/project.pbxproj

Carthage was failing to build this. I believe that with `iPhone Distribution` you need a special profile to sign this library. It works with simply `iPhone Developer`. This shouldn't be an issue for anyone because the frameworks end up being signed with your application's profile when submitting to Apple.

Changed Release signing configuration to "iOS Developer" to improve Carthage compatibility

---

Charts/Classes/Charts/PieChartView.swift

fixes #309
Takes the `selectionShift` into account when calculating the `circleBox`.

fix pie chart clipping

---

Charts/Classes/Data/CandleChartDataSet.swift
Charts/Classes/Renderers/CandleStickChartRenderer.swift
ChartsDemo/Classes/Demos/CandleStickChartViewController.xib

performance enhancement for the candle chart.

Performance Enhancements #29 - candle chart

---

Charts/Classes/Charts/CombinedChartView.swift

For issue #323 
seems we should use same chartXMin and chartXMax
_chartXMin = -0.5
_chartXMax = Double(_data.xVals.count) - 0.5
even there is no bubble data

combined chart - seems we should use same chartXMin and chartXMax even there is no bubble data

---

Charts/Classes/Components/ChartYAxis.swift

I believe the default value should be `false`. It's [false on Android version of the library](https://github.com/PhilJay/MPAndroidChart/blob/2e6bfeb87e2bb0a02fb6350b96a454d77f7c088b/MPChartLib/src/com/github/mikephil/charting/components/YAxis.java#L47). Also I've noticed documentation for `isForceLabelsEnabled` [says](https://github.com/danielgindi/ios-charts/blob/0f33d9fc1e06b0d3685539f3bea5d61bc63000ba/Charts/Classes/Components/ChartYAxis.swift#L238) it's false by default as well.
---
Without the fix:
With the fix:
Note that the values on y axis are nicely calculated.
As a temp workaround fix we can do in our code:
```objective-c
self.chartView.leftAxis.labelCount = self.chartView.leftAxis.labelCount;
```

Fix default value of forceLabelsEnabled

---

README.md

I noticed many people were confused as how to use CocoaPods to install the framework (myself included). I accidentally added the 'ios-charts' pod instead of 'Charts' and spent 10 minutes trying to figure out why it wasn't working. I think a blurb would help many people out.
It's possible it was a contributing factor to these guys having an issue: #277 #283 #289 (mentioning CocoaPods.org having issues) and definitely the reason #47

be explicit on how to install 'Charts' when using CocoaPods since

---

Charts/Classes/Charts/BarLineChartViewBase.swift

When checking for the start of a pan, the pan should not be cancelled when the recognizer's translationInView returns 0 in the direction of scrolling. Seems the iPad more easily returns a zero value in the beginning causing the drag to get cancelled immediately even though the actual drag hasn't started because performPanChange() thinks the chart can't be scrolled anymore. So check to see if the drag has vaules that are not actually 0 before calling performPanChange() to prevent immediate pan cancels.

Start of pan gesture should not be cancelled by no drag

---

Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Charts/HorizontalBarChartView.swift
Charts/Classes/Charts/PieChartView.swift
Charts/Classes/Charts/PieRadarChartViewBase.swift
Charts/Classes/Charts/RadarChartView.swift
Charts/Classes/Components/ChartLegend.swift
Charts/Classes/Renderers/ChartLegendRenderer.swift

Allow the legend to be placed above the chart

Add support for a legend above the chart

---

Charts/Classes/Renderers/ChartAxisRendererBase.swift
Charts/Classes/Renderers/ChartXAxisRenderer.swift
Charts/Classes/Utils/ChartUtils.swift

Hi Daniel,
I have done a few refactorings of the ChartXAxisRenderer that allow the following:
- Now possible to extend the renderer and overwrite selectively the label or line drawing method for a ChartLimitLine (in my project I needed e.g. to draw a triangle as arrow at the top in one case or a short line at the bottom as well as change the label offset, now easily possible)
- Functionally does the same as before
- I have eased the visibility of ChartAxisRendererBase#transformer (easier syntax when extending ChartXAxisRenderer) and ChartUtils#drawText (possible to call the method from the ChartXAxisRenderer extension).
Thanks!
Cheers,
Patrick

Make the ChartXAxisRenderer more flexible: now possible to overwrite drawing the line or label of the ChartLimitLine

---

Charts/Classes/Charts/ChartViewBase.swift

At the moment, noDataText and NoDataTextDescription are drawn overlapped, this pull request fixes the issue.

fixed noDataText and NoDataTextDescription texts ovelapping issue

---

Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Utils/ChartViewPortHandler.swift

Trying to fix issue when there's a maximum / minimum scale and the user tries to pinch the chart further, causing it to slide sideways.

Only alow scaling further if the user can still zoom (Fixes #437)

---

Charts/Classes/Charts/RadarChartView.swift

Setting default skip to 1 might result in unexpected behaviour.

Fix issue related to PhilJay/MPAndroidChart#1121

---

Charts/Classes/Renderers/ChartXAxisRendererBarChart.swift

code review
For bar chart view,```position.x``` of the first label is located horizontally at center of first bar group,and this will lead wrong display.

BUGFIX:fix xAxis labels of bar chart

---

Charts/Classes/Charts/CombinedChartView.swift

if only line data exists and no other data in combined chart, turn _deltaX to 1.0, just like what LineChartView did
This is for https://github.com/danielgindi/ios-charts/issues/329 and what @jwardle asked in my PR #269

if only line data exists and no other data, turn _deltaX to 1.0

---

Charts/Classes/Charts/BarLineChartViewBase.swift

Fixed a bug where panning was disabled in BarLineChart if a drag offset
was set
Could also be merged manually since it is only one line/“!”

Fixed drag offset panning bug

---

Charts/Classes/Components/ChartAxisBase.swift
Charts/Classes/Renderers/ChartXAxisRenderer.swift
Charts/Classes/Renderers/ChartYAxisRenderer.swift

Hi guys.
If the chart is too small the grid lines become blurred. Turning off antialias really helps.
Please take a look.

Add ability to turn off antialias for grid lines

---

Charts/Classes/Charts/BarLineChartViewBase.swift

foundScrollView  will be UITableWrepperView Not UITableView, which will cause TableView Scroll issue

Approved, pending styling: Fix Scroll issue when the graph is in a UITableView

---

Charts/Classes/Charts/BarChartView.swift
Charts/Classes/Charts/HorizontalBarChartView.swift

Make getBarBounds callable from Objective-C code (Fixes #570)

---

Charts/Classes/Charts/BarLineChartViewBase.swift

Old code will cause the visible index incorrect, smaller by 1.
Int() simply cuts the fractional part, which usually isn't the desired behaviour ;) Int(round(f)) does the job
I met this when that the last label should be year 2015, but it actually shows 2014. It turned out that pt.x is 3.9999999999999987, and Int(pt.x) is 3
More information about the casting can be found here:http://stackoverflow.com/questions/24029917/convert-float-to-int-in-swift

round the float value before we cast to Int

---

Charts/Classes/Animation/ChartAnimationEasing.swift

Error : ChartAnimationEasing.swift:345:16: Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

Remove useless parentheses causing swift build error

---

Charts/Classes/Data/ChartDataSet.swift

The force unwrapping in entryCount caused a crash when yVals was nil. Now entryCount returns 0.
#631

Use nil coalescing in ChartDataSet's entryCount (Fixes #631)

---

Charts/Classes/Renderers/ChartLegendRenderer.swift

Just some small changes under the hood.

Adapted ChartLegendRenderer class to upcoming Swift 3 changes and improved code readability

---

Charts/Classes/Charts/RadarChartView.swift
Charts/Classes/Renderers/ChartYAxisRenderer.swift
Charts/Classes/Renderers/ChartYAxisRendererRadarChart.swift

fix code indent problem in ChartYAxisRendererRadarChart, ChartYAxisRenderer, BarChartDataSet, RadarChartView

fix code indent problem in ChartYAxisRendererRadarChart, ChartYAxisRenderer, BarChartDataSet, RadarChartView

---

Charts/Classes/Renderers/LineChartRenderer.swift

In the LineChartRenderers drawLinear method the Context gets saved before checking for existing data.
This leads to never restoring the context, which causes other chart-components to disappear.
This commit fixes this by saving the context after the check for data.
The bug described above can be seen in the two GIFs below:
Relates to #740

LineChartRenderer context bug

---

Charts/Classes/Renderers/LineChartRenderer.swift

Fix for issue #711
Cubic line charts that don’t start at x-index 0 don’t fill correctly
because the fill starts at index 0 (Regular line charts don’t have that
issue). To correct this the index for the fill is taken from the data
entries (similar to regular line chart fill).
Ultimately i think the renderer should be refactored to use a common
code path for filling cubic and regular line charts.

Fix for cubic line chart fill when charts that don't start at x-index 0 #711

---

Charts/Classes/Charts/BarChartView.swift
Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Charts/BubbleChartView.swift
Charts/Classes/Charts/ChartViewBase.swift
Charts/Classes/Charts/CombinedChartView.swift
Charts/Classes/Charts/HorizontalBarChartView.swift
Charts/Classes/Charts/LineChartView.swift
Charts/Classes/Charts/PieChartView.swift
Charts/Classes/Charts/PieRadarChartViewBase.swift
Charts/Classes/Charts/RadarChartView.swift
Charts/Classes/Charts/ScatterChartView.swift

Changed ChartViewBase's _data property declaration from _data! to _data? to allow for setting the chart's data back to nil. Updated the code base to property handle _data as an optional value.

Make ChartViewBase's _data optional. (Fixes #771)

---

Charts/Classes/Charts/BarChartView.swift
Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Charts/BubbleChartView.swift
Charts/Classes/Charts/ChartViewBase.swift
Charts/Classes/Charts/CombinedChartView.swift
Charts/Classes/Charts/HorizontalBarChartView.swift
Charts/Classes/Charts/LineChartView.swift
Charts/Classes/Charts/PieChartView.swift
Charts/Classes/Charts/PieRadarChartViewBase.swift
Charts/Classes/Charts/RadarChartView.swift
Charts/Classes/Charts/ScatterChartView.swift
ChartsDemo/Classes/Demos/AnotherBarChartViewController.m
ChartsDemo/Classes/Demos/BarChartViewController.m
ChartsDemo/Classes/Demos/BubbleChartViewController.m
ChartsDemo/Classes/Demos/CandleStickChartViewController.m
ChartsDemo/Classes/Demos/CombinedChartViewController.m
ChartsDemo/Classes/Demos/CubicLineChartViewController.m
ChartsDemo/Classes/Demos/HorizontalBarChartViewController.m
ChartsDemo/Classes/Demos/LineChart1ViewController.m
ChartsDemo/Classes/Demos/LineChart2ViewController.m
ChartsDemo/Classes/Demos/MultipleBarChartViewController.m
ChartsDemo/Classes/Demos/MultipleLinesChartViewController.m
ChartsDemo/Classes/Demos/NegativeStackedBarChartViewController.m
ChartsDemo/Classes/Demos/PieChartViewController.m
ChartsDemo/Classes/Demos/PositiveNegativeBarChartViewController.m
ChartsDemo/Classes/Demos/RadarChartViewController.m
ChartsDemo/Classes/Demos/ScatterChartViewController.m
ChartsDemo/Classes/Demos/SinusBarChartViewController.m
ChartsDemo/Classes/Demos/StackedBarChartViewController.m

Added an option to the demo charts project view controllers to toggle the charts data to nil or default values. Used test each chart type for pull request #772 to verify that setting the data property causes the chart to properly treat the data as nil.
Note that this pull request includes changes from pr #772. pr #772 should be merged in first and then, if desired, this pr as well.

Add "Toggle Data" option to demo charts. (#771 Support)

---

Charts/Classes/Data/Implementations/Standard/ScatterChartDataSet.swift
Charts/Classes/Data/Interfaces/IBarChartDataSet.swift
Charts/Classes/Data/Interfaces/IBarLineScatterCandleBubbleChartDataSet.swift
Charts/Classes/Data/Interfaces/IBubbleChartDataSet.swift
Charts/Classes/Data/Interfaces/ICandleChartDataSet.swift
Charts/Classes/Data/Interfaces/IChartDataSet.swift
Charts/Classes/Data/Interfaces/ILineChartDataSet.swift
Charts/Classes/Data/Interfaces/ILineRadarChartDataSet.swift
Charts/Classes/Data/Interfaces/IPieChartDataSet.swift
Charts/Classes/Data/Interfaces/IScatterChartDataSet.swift
Charts/Classes/Formatters/ChartDefaultFillFormatter.swift
Charts/Classes/Jobs/AnimatedMoveViewJob.swift
Charts/Classes/Jobs/AnimatedViewPortJob.swift
Charts/Classes/Jobs/AnimatedZoomViewJob.swift
Charts/Classes/Jobs/ChartViewPortJob.swift
Charts/Classes/Jobs/MoveChartViewJob.swift
Charts/Classes/Jobs/ZoomChartViewJob.swift
Charts/Classes/Utils/ChartFill.swift

Add missing UIKit imports for new classes added since #45.

Add missing UIKit imports for iOS 7

---

Charts/Classes/Data/Implementations/Standard/LineChartDataSet.swift
Charts/Classes/Data/Interfaces/ILineChartDataSet.swift
Charts/Classes/Renderers/LineChartRenderer.swift
ChartsDemo/Classes/Demos/LineChart1ViewController.m
ChartsDemo/Classes/Demos/LineChart2ViewController.m
ChartsDemo/Classes/Demos/MultipleLinesChartViewController.m
ChartsDemo/Classes/RealmDemos/RealmLineChartViewController.m
ChartsRealm/Classes/Data/RealmLineDataSet.swift

A new flag was added to ILineChartDataSet and relative implementations. The value of the flag is then used to slightly modify the behavior of drawLinear and generateFilledPath in LineChartRenderer.
The appropriate demo viewControllers were also updated with the new flag.

Feature #539 Stepped line charts

---

Charts/Classes/Charts/BarLineChartViewBase.swift

I’ve added a flag (keepPositionOnRotation) to BarLineChartViewBase indicating whether the chart
should stay at its current position or not
The flag defaults to false to not change any existing behaviour.
This feature was requested/discussed in #786.
The result can be seen in the two picture pairs below:

Keep position on rotation

---

Charts/Classes/Data/Implementations/Standard/PieChartData.swift

The property dataSet on PieChartData did expect a PieChartDataSet and
tried to convert the result. If the user was using a Interface to
represent the data, the pie chart would fail, because the yValueSum method would return 0.0

Type bug in PieChartData

---

Charts/Classes/Charts/RadarChartView.swift
Charts/Classes/Renderers/RadarChartRenderer.swift

For #138 
Add highlight circle for radar chart. It combined an inner filled circle and an outer stroke circle. inner circle fill color, inner circle radius, outer circle radius, stroke width and alpha can be customised.
I notice `drawHighlightLines` is in `LineScatterCandleRadarChartRenderer` now, no longer in the radar chart renderer. I am not sure if draw highlight circle should be here.
Since there are several properties can be asked to customized, I create new properties for radar chart view. 
Let me know if we want to add more customizable properties or it's too many, as well as if the structure needs to be improved.

add highlight circle for radar chart

---

Charts/Classes/Components/ChartYAxis.swift
Charts/Classes/Renderers/ChartYAxisRenderer.swift
ChartsDemo/Classes/Demos/CombinedChartViewController.m
ChartsDemo/Classes/Demos/LineChart2ViewController.m

Stop axis labels duplicating. #315  [Pending squash and cleanup]

---

Charts/Charts.xcodeproj/project.pbxproj
Charts/Classes/Renderers/PiePolylineChartRenderer.swift
ChartsDemo/ChartsDemo.xcodeproj/project.pbxproj
ChartsDemo/Classes/DemoListViewController.m
ChartsDemo/Classes/Demos/PiePolylineChartViewController.h
ChartsDemo/Classes/Demos/PiePolylineChartViewController.m
ChartsDemo/Classes/Demos/PiePolylineChartViewController.xib

Hey guys,
I add new pie chart renderer with polyline indicate, the appearance look like:
please have a look and see if this can merge into master branch  :-)

Add new pie chart renderer with polyline indicate

---

Charts/Classes/Data/Implementations/Standard/PieChartDataSet.swift
ChartsDemo-OSX/ChartsDemo-OSX/Demos/BarDemoViewController.swift
ChartsDemo-OSX/ChartsDemo-OSX/Demos/LineDemoViewController.swift
ChartsDemo-OSX/ChartsDemo-OSX/Demos/PieDemoViewController.swift
ChartsDemo-OSX/ChartsDemo-OSX/Demos/RadarDemoViewController.swift

Forked it, tried it, fixed a small thing not compiling in Xcode 7.3, added some obvious descriptions to the OSX demo.

Some minor nits

---

Charts/Classes/Data/Implementations/Standard/ChartDataSet.swift
Charts/Classes/Data/Implementations/Standard/LineChartDataSet.swift
Charts/Classes/Data/Interfaces/ILineChartDataSet.swift
Charts/Classes/Renderers/LineChartRenderer.swift
ChartsDemo/Classes/Demos/CubicLineChartViewController.m
ChartsDemo/Classes/Demos/LineChart1ViewController.m
ChartsDemo/Classes/Demos/LineChart2ViewController.m
ChartsRealm/Classes/Data/RealmLineDataSet.swift

Horizontal cubic line

---

Charts/Classes/Data/Implementations/Standard/BarChartDataSet.swift
Charts/Classes/Data/Implementations/Standard/BubbleChartDataSet.swift
Charts/Classes/Data/Implementations/Standard/CandleChartDataSet.swift
Charts/Classes/Data/Implementations/Standard/ChartDataSet.swift
ChartsRealm/Classes/Data/RealmBarDataSet.swift
ChartsRealm/Classes/Data/RealmBaseDataSet.swift
ChartsRealm/Classes/Data/RealmBubbleDataSet.swift
ChartsRealm/Classes/Data/RealmCandleDataSet.swift

fix #940. another start ... endValue crash
use stride instead.
I searched there are many ... and ..<, I'm not sure how many loop is in danger... right now we can only fix what we have met.

fix #940. another loop bounds crash

---

Charts/Classes/Charts/ChartViewBase.swift

fa5d01f introduced a crash when using a MarkerView with a PieChartView – because PieChartView no longer has an `_xAxis`, any attempt to call `drawMarkers` will crash [here](https://github.com/danielgindi/Charts/blob/b1dcdbd25f4b3bff3fba9c9593fcede1bb148617/Charts/Classes/Charts/ChartViewBase.swift#L533). I'm not sure if this is the ideal fix with how you've been refactoring the ChartView classes, but it does restore the ability to use markers with a pie chart.

Fix a crash when using markers with a PieChart

---

Charts/Classes/Charts/BarChartView.swift
Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Charts/ChartViewBase.swift
Charts/Classes/Charts/HorizontalBarChartView.swift
Charts/Classes/Charts/PieRadarChartViewBase.swift
Charts/Classes/Data/Implementations/ChartBaseDataSet.swift
Charts/Classes/Data/Implementations/Standard/ChartData.swift
Charts/Classes/Data/Implementations/Standard/ChartDataSet.swift
Charts/Classes/Data/Implementations/Standard/CombinedChartData.swift
Charts/Classes/Data/Interfaces/IChartDataSet.swift
Charts/Classes/Highlight/BarChartHighlighter.swift
Charts/Classes/Highlight/ChartHighlight.swift
Charts/Classes/Highlight/ChartHighlighter.swift
Charts/Classes/Highlight/CombinedHighlighter.swift
Charts/Classes/Highlight/HorizontalBarChartHighlighter.swift
Charts/Classes/Renderers/BubbleChartRenderer.swift
Charts/Classes/Renderers/CombinedChartRenderer.swift
Charts/Classes/Utils/ChartSelectionDetail.swift
Charts/Classes/Utils/ChartUtils.swift
ChartsRealm/Classes/Data/RealmBaseDataSet.swift

There are certain cases (ie. bubbles) which make sense to have multiple
values per xIndex.
This fixes that - and adds more granular highlight for Combined Chart.

Highlight enhancements (Closes #654, closes #702)

---

Charts/Classes/Data/Implementations/Standard/LineChartDataSet.swift
Charts/Classes/Data/Interfaces/ILineChartDataSet.swift
Charts/Classes/Renderers/LineChartRenderer.swift
ChartsRealm/Classes/Data/RealmLineDataSet.swift

Property circleHoleRadius added to ILineChartDataSet protocol. The new circleHoleRadius value is set only if it is less than circleRadius. Otherwise a default value (4.0) is used.

Property circleHoleRadius added to ILineChartDataSet protocol. 

---

Charts/Classes/Components/ChartLimitLine.swift
Charts/Classes/Renderers/ChartXAxisRenderer.swift
Charts/Classes/Renderers/ChartXAxisRendererHorizontalBarChart.swift
Charts/Classes/Renderers/ChartYAxisRenderer.swift
Charts/Classes/Renderers/ChartYAxisRendererHorizontalBarChart.swift

add a switch whether to draw limit line's labels. default is true

add a switch whether to draw limit line's labels. default is true

---

Charts/Cartfile.private

hopefully this fix the ios-test-case bug for a long time, according to #1082 @ikesyo's fix
once the fix is tagged, we can change back to >~ format, use master for now

update iso-snapshot-test-case to master to have the fix for now

---

.travis.yml
Charts/Cartfile.resolved
Rakefile

upgrade carthage, resolve test failure config
remove tvos test target, and specify commit for building

upgrade carthage, resolve test failure config

---

.travis.yml
Charts/Cartfile.private
Charts/Cartfile.resolved

update ios-snapshot-test-case to 2.1.2
remove brew upgrade carthage, because travis seems updated carthage
```
$ brew upgrade carthage
Error: carthage 0.17.2 already installed
The command "brew upgrade carthage" failed and exited with 1 during .
Your build has been stopped.
/Users/travis/build.sh: line 109: shell_session_update: command not found
```

remove brew upgrade carthage for travis and update ios-snapshot-test-case to 2.1.2

---

Charts/Classes/Charts/BarLineChartViewBase.swift

Seeing some users don't know how to use setVisibleRange APIs (can only be called after we have data, otherwise no effect). For now, add the API description for this

improve comment to warn users how to use setVisibleRange APIs

---

Charts/Classes/Animation/ChartAnimator.swift
Charts/Classes/Charts/BarLineChartViewBase.swift
Charts/Classes/Charts/PieRadarChartViewBase.swift
Charts/Classes/Jobs/AnimatedViewPortJob.swift
Charts/Classes/Utils/ChartPlatform.swift

This is originally from #1266 
convert RunLoopMode to swift 3.0 syntax and remove redundancy
The new Apple documentation says the function signature is 
```swift
func add(to runloop: RunLoop, forMode mode: RunLoopMode)
```
while the old document says
```swift
func addToRunLoop(_ runloop: NSRunLoop, forMode mode: String)
```

convert RunLoopMode to swift 3.0 syntax

---

Charts/Classes/Renderers/CombinedChartRenderer.swift

for #1208, seems `drawBarShadowEnabled` should be false by default
@danielgindi not sure what you think? Intended or misused

for #1208, seems drawBarShadowEnabled should be false by default

---

ChartsRealm/Classes/Data/RealmBarDataSet.swift
ChartsRealm/Classes/Data/RealmBaseDataSet.swift
ChartsRealm/Classes/Utils/RealmChartUtils.swift

fix attempt for Realm support, refer to
https://github.com/realm/realm-cocoa/commit/7d5a1b86b5afe1b51f549af4fefe9f04f0380c46

fix attempt for Realm support

---

ChartsDemo/ChartsDemo.xcodeproj/project.pbxproj

I don't know why but my Xcode 8 prompts me this change..

migrate more ChartsDemo project setting to swift 3.0

---

Charts/Classes/Charts/BarChartView.swift
Charts/Classes/Charts/PieRadarChartViewBase.swift

Fixing two issues:
1. BarChart right/left bar cut in half (Issue #1446) notes that if you turn on `fitBars`, the last bar will be cropped out.
2. Tapping on a pie chart slice would not trigger any delegate callbacks (no issue). This is fixed by explicitly requesting callbacks in PieRadarChartViewBase’s tap event.

Fix bar layout bug, pie callback bug

---

Charts.xcodeproj/project.pbxproj

Project settings don't need to be set to iOS. Due to having a single target they need to be macOS which has been set in the project's main settings.
Please read the article [here](http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/) for more info.

Don't override project settings in targets

---

Charts/Classes/Renderers/LineChartRenderer.swift

#1421
This is due to Swift 3.0 has 
>func strokeLineSegments(between points: [CGPoint]) 
while swift 2.x is
>CGContextStrokeLineSegments(context, _lineSegments, size)

[swift 3.0 specific]fix linear line chart additional line segments wile zooming in

---

.travis.yml
README.md

Adds Codecov to promote test coverage!

Adds Codecov

---

Rakefile

I believe that codecov says 0% because our Realm tests have no tests.

Fix codecov

---

Charts.xcodeproj/project.pbxproj
Source/Charts/Utils/ChartUtils.swift
Tests/Charts/ChartUtilsTests.swift

Closes #1550, #1540, #1491
I added some tests based on the crash mentioned in #1550 and there was a crash when using DBL_MAX as the input of the `decimals` function. 
There are still some abnormalities in the `decimals` function I believe. In MPAndroidCharts I ran the same tests and it returns 2 not zero for all these cases except for the ones that crash and return negative Int max.
This pull request fixes the crash but I don't think the `decimals` function does what we want it to do.
@danielgindi, @PhilJay what is this function actually supposed to do?

Fix decimals crash in ChartsUtil

---

Source/Charts/Components/AxisBase.swift
Source/Charts/Renderers/AxisRendererBase.swift

Attempt to fix #1488, #1564
@danielgindi I need you carefully review this and give details about existing implementation about centerAxisLabels feature. My changes may lack of information and cause more issues, though I have tesed it in time line chart, bar chart, combined chart, multiple bar chart, line chart.
1. I removed the dependency of getting initial `n` value, because `first` and `last` will be equal after zooming a lot
2. I change `centerAxisLabelsEnabled` condition, if entry count > 0, we could turn on centerAxisLabel. I need context why it's `> 1`.
3. I removed using local variable `centeringEnabled`, because `axis.entries` would be changed but `centeringEnabled` keeps reading old entryCount, which seems a dirty read issue
4. I use `offset: Double = interval / 2.0` instead of …

Bugfix for fix #1488, #1564

---

Source/Charts/Components/AxisBase.swift

fix #1603 and API comment. Looks like typo, but I changed the order to highlight the difference

fix #1603 and API comment

---

ChartsDemo/Classes/Demos/MultipleBarChartViewController.xib

Removed width constraint on slider-text-x and slider-text-y, so width  can adjust automatically based on set text. Also added equal-width
constraint on slider-text-x in relation to slider-text-y, so the width
of both will always be the same.

Updated Width Constraints - Fixes #1770

---

Source/Charts/Utils/ChartPlatform.swift

Fixes the bug mentioned in #1780 but with a fix that compiles.

Fix png image using JPEG type when being saved on macOS

---

Source/Charts/Utils/ChartUtils.swift

There needs to be a check against NaN after ChartUtils::roundToNextSignificant() returns.

Added a check against NaN

---

Source/Charts/Data/Implementations/Standard/CandleChartDataEntry.swift

Fix few typos in `copyWithZone` method.

Fix NSCopying implementation in CandleChartDataEntry

---

Charts.podspec

Bumped the dependency version from 1.1 to 2.1.1 because it was preventing me from using the latest RealmSwift(2.1.2) with Charts, but thought it would be a good idea to keep it in line with what's in the Cartfile

Update Podspec RealmSwift Dependency to 2.1.1 to be in line with Cartfile

---

Source/Charts/Components/Legend.swift

fix a typo, as orientation is horizontal by default

fix a typo, as orientation is horizontal by default

---

Charts.xcodeproj/project.pbxproj
ChartsDemo/ChartsDemo.xcodeproj/project.pbxproj
Rakefile

ChartsRealm now depends on RealmSwift. Fixed up the demo and test targets to work with this change.
closes #2066

Fix demo and test targets not running/testing

---

ChartsDemo/Supporting Files/Info.plist

Adds NSPhotoLibraryUsageDescription to plist of ChartsDemo to prevent crash on iOS 10 on try to store shot of char to photo library.

Adds NSPhotoLibraryUsageDescription to plist of ChartsDemo

---

Source/Charts/Data/Implementations/Standard/ChartDataEntryBase.swift

This fixes the following build error in Xcode 8.3 beta
>/.../Charts/Source/Charts/Data/Implementations/Standard/ChartDataEntryBase.swift:61:40: Binary operator '!==' cannot be applied to operands of type 'AnyObject?!' and 'AnyObject?'

Fixes Xcode 8.3 beta build issue

---

Source/Charts/Data/Implementations/Standard/ChartDataSet.swift

Fixes index out of range crash.

---

Source/Charts/Charts/BarLineChartViewBase.swift

When enabled autoScale.
`data.calcMinMaxY(fromX: self.lowestVisibleX, toX: self.highestVisibleX)` is called after 
` _leftYAxisRenderer?.computeAxis(min: _leftAxis._axisMinimum, max: _leftAxis._axisMaximum, inverted: _leftAxis.isInverted)`
`_rightYAxisRenderer?.computeAxis(min: _rightAxis._axisMinimum, max: _rightAxis._axisMaximum, inverted: _rightAxis.isInverted)`
`_xAxisRenderer?.computeAxis(min: _xAxis._axisMinimum, max: _xAxis._axisMaximum, inverted: false)`
that means _leftAxisRenderer and _rightAxisRenderer will render AxisLines and Values based on old values of _axisMinimum, _axisMaximum

Fixed the inconsistency of AxisMax and AxisMin

---

Source/Charts/Animation/ChartAnimationEasing.swift
Source/Charts/Data/Implementations/Standard/ChartData.swift
Source/Charts/Data/Implementations/Standard/ChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ChartDataEntryBase.swift
Source/Charts/Data/Implementations/Standard/ChartDataSet.swift
Source/Charts/Data/Implementations/Standard/CombinedChartData.swift
Source/Charts/Highlight/RadarHighlighter.swift
Source/Charts/Renderers/PieChartRenderer.swift
Source/Charts/Utils/ChartUtils.swift

Remove deprecations related to M_PI, M_PI_2, DBL_MAX, and DBL_EPSILON, which are deprecated in Swift 3.0.

remove deprecation warnings in XCode 8.3 

---

Source/Charts/Animation/ChartAnimationEasing.swift
Source/Charts/Data/Implementations/Standard/ChartData.swift
Source/Charts/Data/Implementations/Standard/ChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ChartDataEntryBase.swift
Source/Charts/Data/Implementations/Standard/ChartDataSet.swift
Source/Charts/Data/Implementations/Standard/CombinedChartData.swift
Source/Charts/Highlight/RadarHighlighter.swift
Source/Charts/Renderers/PieChartRenderer.swift
Source/Charts/Utils/ChartUtils.swift
Source/ChartsRealm/Data/RealmBarDataSet.swift
Source/ChartsRealm/Data/RealmBaseDataSet.swift
Source/ChartsRealm/Data/RealmBubbleDataSet.swift
Source/ChartsRealm/Data/RealmCandleDataSet.swift
Tests/Charts/ChartUtilsTests.swift

Xcode 8.3 introduces a bunch of new compiler warnings. This PR fixes them.
* Replace `M_PI_2` with `Double.pi / 2`
* Replace `M_PI` with `Double.pi`
* Replace `DBL_MAX` with `Double.greatestFiniteMagnitude`
* Replace `DBL_EPSILON` with `Double.ulpOfOne`

Fix Xcode 8.3 compiler warnings

---

.travis.yml
Charts.xcodeproj/project.pbxproj
Charts.xcodeproj/xcshareddata/xcschemes/Charts.xcscheme
Rakefile
scripts/copy-carthage-frameworks.sh

update device id in Travis CI and xcode 8.3 image

Update Travis config for Xcode 8.3 and fix test failures

---

Source/Charts/Charts/ChartViewBase.swift

fixing a bug: when clearing chart, the 'lastHighlighted' var isn't set to nil. This will cause user to tap twice to highlight the new value, if the new value's index is the same as the old lastHighlighted's.

Bug fixing with one line, updating ChartViewBase.swift

---

Source/Charts/Charts/ChartViewBase.swift

fix #2222 
move default backgroundColor to initialize() as `initWithCoder` also needs it
I checked initialize() is only called in init(), so it seems safe to move there, to avoid duplicated code.

fix #2222 move default backgroundColor to initialize()

---

Rakefile

remove build for ci tests procedure, use `clean test` directly
Seems travis is building Charts twice due to `build` and `test`. But sometimes, on my machine it's just once and sometimes twice.

remove build for ci tests procedure, use `clean test` directly

---

Source/Charts/Charts/ChartViewBase.swift

`notifyDataSetChanged()` may actually mutate some of the view port properties — stomping all over what the view port jobs just accomplished.
This behavior is apparent when calling `moveViewToX()` on the chart view that has no frame yet. Prior to this change, calling `moveViewToX()` had no affect on a chart a chart that has no frame. That's because once the chart view was assigned a frame, `notifyDataSetChanged()` call would actually mutate the view port's properties stomping all over what the view port jobs just finished doing.

Run view port jobs afterwards (Fixes #2395)

---

Source/Charts/Data/Implementations/Standard/ChartDataSet.swift

The last entry is ignored.
If the last value is the max or min, the range will be wrong

Fixed, If the last value is the max or min, the range will be wrong

---

ChartsDemo/Classes/Components/BalloonMarker.swift

Getting rid of not needed String-NSString bridging

Minor improvements in BalloonMarker.swift

---

Source/Charts/Charts/ScatterChartView.swift

fix #1879. Similar cut in half issue in scatter chart like others
@danielgindi please review. I think we met this several times. Not sure if we should put them together

Fix #1879. Similar cut in half issue in scatter chart like others

---

Source/Charts/Renderers/LegendRenderer.swift

fix #2099, avoid crash when some chart only allow 1 data set but people will set more than that

fix #2099, avoid crash when some chart only allow 1 data set

---

README.md

I created a tutorial along with putting code on GitHub and was hopping to have it publicised?

Adding a third party tutorial

---

Source/Charts/Renderers/ChartDataRendererBase.swift
Source/Charts/Renderers/HorizontalBarChartRenderer.swift

Adding a `self.` reference to a instance variable reduced the compile
time significantly (over 10x improvement). A single line evaluation of a
variable was further broken out into separate steps to reduce the
compile time as well.
This cuts at least 2 seconds from the build time
Compile times were analyzed with the following bash command:
`xcodebuild -scheme Charts -sdk iphonesimulator PLATFORM_NAME=iphonesimulator clean build OTHER_SWIFT_FLAGS="-Xfrontend -debug-time-function-bodies" 2>&1 | grep -e [0-9][0-9].[0-9].ms | sort -nr`
Compile times before the change:
Compile times after the change:

Reduce build time with minor reference refactor

---

README.md

Just added link to beginner-friendly tutorial / example using a couple of the charts with Swift and setting up (not using Realm)

tutorial link added to readme

---

Source/Charts/Utils/Platform.swift

Compiling the framework with Xcode 9 beta 4 results in error due to macOS Swift api changes.
This pull request resolves that.

Conform to macOS api changes in swift 3.2

---

Source/Charts/Charts/CombinedChartView.swift
Source/Charts/Data/Implementations/Standard/CombinedChartData.swift

Fix CombinedChartView not draw markers

---

Source/Charts/Charts/BarLineChartViewBase.swift

Currently if a chart is inside a scroll view and drag is enabled, the chart pan gesture recognizes all pan events and the containing scroll view doesn't work. 
This PR allows enabling/disabling drag in either axis separately. Probably the most common use case would be enabling scale only in the X direction and enabling drag only in the X direction, so a vertically scrolling scroll view can work normally:
```
chartView.scaleYEnabled = false
chartView.scaleXEnabled = true
chartView.dragYEnabled = false
```

Allow turning off drag in X and Y axes separately.

---

Source/Charts/Components/Description.swift
Source/Charts/Data/Interfaces/IChartDataSet.swift
Source/Charts/Filters/DataApproximator.swift
Source/Charts/Highlight/Highlight.swift
Source/Charts/Renderers/Scatter/ChevronDownShapeRenderer.swift
Source/Charts/Renderers/Scatter/ChevronUpShapeRenderer.swift
Source/Charts/Renderers/Scatter/CircleShapeRenderer.swift
Source/Charts/Renderers/Scatter/CrossShapeRenderer.swift
Source/Charts/Renderers/Scatter/IShapeRenderer.swift
Source/Charts/Renderers/Scatter/SquareShapeRenderer.swift
Source/Charts/Renderers/Scatter/TriangleShapeRenderer.swift
Source/Charts/Renderers/Scatter/XShapeRenderer.swift

- Added missing `import CoreGraphics` where needed.
- Added missing `import UIKit` where needed.

Compatibility with swift playgrounds

---

ChartsDemo-OSX/ChartsDemo-OSX/Demos/BarDemoViewController.swift

fix #2890. Turned out it's multiple bar chart but not grouped 
calling group bars will result in:

fix #2890. Turned out it's multiple bar chart but not grouped

---

Source/Charts/Components/IMarker.swift
Source/Charts/Formatters/IAxisValueFormatter.swift
Source/Charts/Formatters/IValueFormatter.swift
Source/Charts/Highlight/IHighlighter.swift
Source/Charts/Renderers/Scatter/IShapeRenderer.swift

`class` is better as it allows Swift classes to avoid the `NSObject` overhead.
the @objc tag on any classes that may adopt the protocol enforces `NSObject` adoption.

Replaced unnecessary NSObjectProtocol

---

Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Components/AxisBase.swift
Source/Charts/Renderers/XAxisRenderer.swift
Source/Charts/Renderers/XAxisRendererHorizontalBarChart.swift
Source/Charts/Renderers/YAxisRenderer.swift
Source/Charts/Renderers/YAxisRendererHorizontalBarChart.swift

character is deprecated.
As for "count character" code, delete "character" code.
You will delete deprecated alert.

modify for Character Alert: characters is deprecated

---

Package.swift

This implements https://github.com/danielgindi/Charts/issues/753 by adding a Package.swift file.

Add Swift Package Manager support.

---

Source/Charts/Animation/Animator.swift
Source/Charts/Charts/BarLineChartViewBase.swift
Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Charts/CombinedChartView.swift
Source/Charts/Charts/PieChartView.swift
Source/Charts/Charts/PieRadarChartViewBase.swift
Source/Charts/Charts/RadarChartView.swift
Source/Charts/Components/MarkerImage.swift
Source/Charts/Components/MarkerView.swift
Source/Charts/Data/Implementations/Standard/BarChartData.swift
Source/Charts/Data/Implementations/Standard/BarChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/BubbleChartData.swift
Source/Charts/Data/Implementations/Standard/LineChartDataSet.swift
Source/Charts/Data/Implementations/Standard/PieChartData.swift
Source/Charts/Data/Implementations/Standard/ScatterChartData.swift

an attempt to reduce the number of force unwraps

unwrap optionals

---

Source/Charts/Data/Implementations/Standard/PieChartDataSet.swift
Source/Charts/Data/Interfaces/IPieChartDataSet.swift
Source/Charts/Renderers/PieChartRenderer.swift

Added attribute `highlightColor` to specify a color for highlighted pie chart sectors.

added highlightColor parameter for pie charts

---

Source/Charts/Renderers/XAxisRenderer.swift
Source/Charts/Renderers/XAxisRendererHorizontalBarChart.swift
Source/Charts/Utils/ChartUtils.swift

Improves readability and clarity

Replaced `ChartUtils` methods with `CGSize` extensions

---

Source/Charts/Charts/BarLineChartViewBase.swift
Source/Charts/Charts/PieRadarChartViewBase.swift

Removed `isKind(of:)`

---

Source/Charts/Charts/BarLineChartViewBase.swift
Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Charts/CombinedChartView.swift
Source/Charts/Charts/PieRadarChartViewBase.swift
Source/Charts/Charts/RadarChartView.swift
Source/Charts/Components/AxisBase.swift
Source/Charts/Data/Implementations/ChartBaseDataSet.swift
Source/Charts/Data/Implementations/Standard/BubbleChartDataSet.swift
Source/Charts/Data/Implementations/Standard/ChartData.swift
Source/Charts/Data/Implementations/Standard/ChartDataSet.swift
Source/Charts/Highlight/ChartHighlighter.swift
Source/Charts/Highlight/RadarHighlighter.swift
Source/Charts/Jobs/AnimatedViewPortJob.swift
Source/Charts/Jobs/AnimatedZoomViewJob.swift
Source/Charts/Jobs/ViewPortJob.swift
Source/Charts/Jobs/ZoomViewJob.swift
Source/Charts/Renderers/BarChartRenderer.swift
Source/Charts/Renderers/BarLineScatterCandleBubbleRenderer.swift
Source/Charts/Renderers/CombinedChartRenderer.swift
Source/Charts/Renderers/RadarChartRenderer.swift
Source/Charts/Renderers/XAxisRendererHorizontalBarChart.swift
Source/Charts/Renderers/YAxisRenderer.swift
Source/Charts/Utils/Transformer.swift

Since the framework is entirely Swift, internal properties do not need to be marked as @objc

Removed @objc from internal properties

---

Source/Charts/Charts/BarLineChartViewBase.swift

Unfortunately https://github.com/danielgindi/Charts/commit/3c083f32ec7399b7c43647fa305752e370c7e800 broke my change.
The use case when the problem appears is when a chart is embedded in a scroll view. Disabling y axis dragging should enable the scroll view to be used for vertical scrolling with the finger on the chart.
The change in this PR is required for this to work.

Fix turning off drag in X and Y axes separately.

---

Source/Charts/Renderers/XAxisRendererHorizontalBarChart.swift

for #2745. chart should be weak.
#2772 is unclear

for #2745. chart should be weak.

---

Source/Charts/Jobs/AnimatedViewPortJob.swift

for #3061
revert animationUpdate() and animationEnd()
not trigger crash if subclass does nothing

for #3061 fix animation crash

---

ChartsDemo/Objective-C/Demos/HalfPieChartViewController.m
ChartsDemo/Objective-C/Demos/LineChart1ViewController.m
ChartsDemo/Objective-C/Demos/LineChart2ViewController.m
ChartsDemo/Objective-C/Demos/LineChartTimeViewController.m
ChartsDemo/Objective-C/Demos/MultipleLinesChartViewController.m
ChartsDemo/Objective-C/Demos/PieChartViewController.m

Makes ChartsDemo compiling again

---

Source/Charts/Renderers/XAxisRendererHorizontalBarChart.swift

Fixed using wrong axis (Issue #2257)

---

Rakefile

To avoid any refactoring change that will impact demo builds like #3116, I added the build process for ChartsDemo and its swift portion.
Completely new to rake, it's weird google does not give enough tutorials towards rake  basis.
It took me a wild guess what's the difference between `is_build_demo = false` and `is_build_demo: false` as I just follow `xcprety_args: ''` to guess it's the right way to specify default value.
I change to 'ChartsDemo/ChartsDemo.xcodeproj' as umbrella project. 
I specifically put build before test, to list test results at the bottom of the output.
One thing I don't know why is it builds Charts framework triple times, though I don't ask for clean. It's what we could improve, so welcome suggestions.

add option to build demo projects unit tests on iOS

---

Charts.xcodeproj/project.pbxproj
Source/Charts/Filters/DataApproximator+N.swift

This implementation does not require tolerance for approximation and takes number of resulting points as parameter instead.
Uses modified Douglas-Peucker algorithm described here - http://psimpl.sourceforge.net/douglas-peucker.html

added DataApproximator+N extension

---

Source/Charts/Renderers/AxisRendererBase.swift

Find another issue when testing  #3114
fix axis label missing when zoom in deep enough, sometimes the label will disappear while scrolling.
Turned out `first` and `last` is equal, so `n` remains 0, and `axis.entries` is empty then.
I do see `var n = axis.centerAxisLabelsEnabled ? 1 : 0` at first, but rather than force setting n = 1, I think checking n == 0 specifically may be better. Welcome suggestions.

Fix axis label disappear when zooming in deep enough

---

Source/Charts/Charts/BarLineChartViewBase.swift
Source/Charts/Charts/PieChartView.swift
Source/Charts/Charts/PieRadarChartViewBase.swift
Source/Charts/Charts/RadarChartView.swift

I was trying to subclass the LegendRenderer for a custom pie chart legend, but swapping the `legendRenderer` property didn't take any effect because the internal var was used instead of the open one.

Subclassing of LegendRenderer didn't take any effect

---

Source/Charts/Components/AxisBase.swift

This change adds the ability to users to override the imposed limitation of at least 2 labels per axis and at most 25 labels per axis if they need to and at their own risk. 
By default these customizable limits are hardcoded to the previous limits, at least 2 labels, at most 25.
The rationale for this change is that when coming from previous versions of Charts, users are able to use –at least on the X axis– as many labels as they wish and when they upgrade to a newer version of Charts they find that they have lost functionality, and this change brings that functionality back.

Give the users customizable axis label limits (Fixes #2085)

---

Source/Charts/Charts/BarLineChartViewBase.swift
Source/Charts/Charts/ChartViewBase.swift

There was an issue with reseting the _highlight_ manually from code. The _lastHighlighted_ property of **ChartViewBase** was not set to nil. Thus, calling  **chartView.highlightValue(nil)** in the delegate method  _chartValueSelected(_ chartView: entry: highlight:)_ did not do anything, and the next time user tapped a bar the chartValueNothingSelected method was called instead of the intended chartValueSelected.

fix programatical unhighlighting for BarCharView

---

Source/Charts/Formatters/IndexAxisValueFormatter.swift

Fixes #3154
Corrected a mistake in the guard statement.

Fixed X-Axis Labels Not Showing (#3154)

---

ChartsDemo/Swift/Components/BalloonMarker.swift

Consider insets, adjust the position of the label in the context of the center.

Fix BalloonMarker's text position calculation, consider insets

---

Source/Charts/Renderers/AxisRendererBase.swift
Source/Charts/Renderers/YAxisRendererRadarChart.swift

For #2356 
This is a corner case when `interval` and `intervalMagnitude` meet certain conditions, like `interval=0.06` and `intervalMagnitude=0.01` will lead `floor(10.0 * intervalMagnitude)` to `0.0`, and crash at `axis.decimals = Int(ceil(-log10(interval)))`
I added a check if it's 0, then we keep the current interval. 
@danielgindi Need you to review this as this is a fundamental change.
The problem is I don't know whether to keep the interval value, or we use `intervalMagnitude * 5` such as to get 0.05 rather than 0.06 or 0.08.
Or, do we have other options?

fix #2356 crash if floor(10.0 * intervalMagnitude) is 0.0

---

Source/Charts/Charts/ChartViewBase.swift

when chart view already rendered, if updating the chartData with nil, it will not rerender, and display the old content
call setNeedsDisplay() here to trigger render noDataText

Call setNeedsDisplay() to trigger render noDataText

---

ChartsDemo/Objective-C/Components/BalloonMarker.swift
ChartsDemo/Swift/Components/BalloonMarker.swift

Balloon Marker indicates position of data

---

Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Highlight/Highlight.swift

for #2840. add dataIndex parameter in `highlightValue()` calls. Default is -1

For #2840. add dataIndex parameter in `highlightValue()` calls

---

ChartsDemo/Objective-C/Demos/RadarChartViewController.m
Source/Charts/Components/MarkerView.swift

Hi there;
why this pull request:
If you use the Charts Framework from another Bundle, this method will not find the ressources as this is looking in the main bundle only.
I added a method to be able to load the ressources from a given bundle.
Thanks,
Denis

Support other bundle than main MarkerView.viewFromXib()

---

Source/Charts/Data/Implementations/Standard/ChartDataSet.swift

for https://github.com/danielgindi/Charts/issues/3166
Temporary fix for calcMinMax frequency.
Better implementation coming for Charts 4

Restored old performance in ChartDataSet

---

Source/Charts/Data/Implementations/Standard/ChartDataSet.swift

Fixes issue #3260 
The min and max values of `ChartDataSet` should always be reset to their default values when `clear()` is called. Since `clear()` removes all items from `values`, the guard statement prevents this reset from happening. Moving the guard statement won't have any impact on the rest of the project.

Min and Max reset when clearing ChartDataSet (Fixes #3260)

---

ChartsDemo/Objective-C/Components/BalloonMarker.swift
ChartsDemo/Swift/Components/BalloonMarker.swift

#3287: align Objc and Swift demos balloon marker

Align Objc and Swift demos balloon marker

---

ChartsDemo/Supporting Files/Info.plist
Source/Charts/Jobs/ZoomViewJob.swift

Will pick a few before releasing 3.1
1. revert a mistake, fix #3299
2. add one more key for iOS 11 camera roll saving. fix #3311

minor bug fix in favor of 3.1 release

---

ChartsDemo/Objective-C/DemoBaseViewController.m

Fixes static analyzer issue complaining  -[tableView:cellForRowAtIndexPath:] returns nil.

Refactors -[tableView:cellForRowAtIndexPath:]

---

Source/Charts/Data/Implementations/Standard/PieChartData.swift

fix #3146. add a warning message if pie chart has more than one data set
I specifically call super because we actually did nothing in pie chart.

for #3146. add a warning message if pie chart has more than one data set

---

README.md
Source/Supporting Files/Info.plist

bump to 3.1 release

---

Source/Charts/Charts/BarLineChartViewBase.swift

#2963 
Support cases where the clipping of data produces unwanted visual issues by adding an option to disable it.

Add option to disable clipping data to contentRect

---

Source/Charts/Charts/BarLineChartViewBase.swift

Currently, turning off drag in X and Y Axis separately is only available for Swift.
This PR adds objective-c compatible for enabling/disabling drag in either axis separately.
Add `@objc` tag for `dragXEnabled`, `dragYEnabled` properties.

Add Objective-c compatible for turning off drag in X and Y Axis separately

---

ChartsDemo-iOS/Objective-C/Demos/CandleStickChartViewController.m
ChartsDemo-iOS/Swift/DemoBaseViewController.swift
ChartsDemo-iOS/Swift/Demos/CandleStickChartViewController.swift

update candle chart view options in demo project to toggle showing candle bar

update candle chart view options in demo project

---

Source/Charts/Components/AxisBase.swift
Source/Charts/Components/ChartLimitLine.swift
Source/Charts/Data/Implementations/Standard/CandleChartDataSet.swift
Source/Charts/Data/Implementations/Standard/LineChartDataSet.swift
Source/Charts/Data/Implementations/Standard/LineRadarChartDataSet.swift
Source/Charts/Utils/ChartUtils.swift

Adding convenience function. There is discussion in the Swift forums about adding this to the language, so we may be able to remove it in the future.

Added clamping function for `Comparable`

---

ChartsDemo-iOS/Swift/DemoBaseViewController.swift
ChartsDemo-iOS/Swift/Demos/LineChart1ViewController.swift
Source/Charts/Data/Implementations/Standard/LineChartDataSet.swift
Source/Charts/Data/Interfaces/LineChartDataSetProtocol.swift
Source/Charts/Renderers/LineChartRenderer.swift
Source/Charts/Utils/Platform.swift

Some stabilization and code cleanup.
@jjatie could you please take a look at this PR. This PR stabilises and improves your PR #3142

Added gradient line drawing to LineChartRenderer. based on PR #3142

---

Source/Charts/Charts/ChartViewBase.swift

The main idea behind this pull request is to make the legend renderer externally customizable and overridable.
Our customer's request was to detect when the user's clicks on a legend and to highlight corresponding line on the chart.
By making public the legendRenderer property (similarly to the renderer property) we would like to use our own legend renderer class which stores the exact location of the labels and in this way we can detect if the user clicked on a label or not.

Make legendRenderer property public in order to be externally customizable

---

Source/Charts/Components/YAxis.swift
Source/Charts/Renderers/YAxisRendererRadarChart.swift

If the user chooses not to display the inner web, the adjusted x position for y axis labels in a `RadarChartView()` looks off, therefore this commit introduces two additional properties that allow for centering these labels.
The renderer used a hardcoded value of `10.0` points to shift the labels to the right, this has been changed to include a new property (`labelXOffset`) to let the user configure this value for their needs.
The `NSTextAlignment` for rendering the labels was also hardcoded to `.left`, I've introduced a new property called `labelAlignment` to allow users to configure this if needed.
Both of the previously hardcoded values have been set as the default value for the newly added properties.
No testing has been added as part of these changes.

Add more render options for y axis labels

---

Source/Charts/Components/LegendEntry.swift
Source/Charts/Renderers/LegendRenderer.swift

Adds a color setting to legend entries to customize labels. Addresses the feedback in #2640.

Add label colors to legend entries

---

Source/Charts/Renderers/BarChartRenderer.swift

when bottom equals top, offset is not necessary
fix  #3586

update barRect.size.height calculation

---

Source/Charts/Formatters/IValueFormatter.swift

Updated the documentation markup in the IValueFormatter protocol by changing the reference to getFormattedValue() to the newer stringForValue() method.

Changed comment that referenced getFormattedValue() method in IValueFormatter

---

Charts.xcodeproj/project.pbxproj
ChartsDemo-iOS/Objective-C/Components/BalloonMarker.swift
ChartsDemo-iOS/Swift/Components/BalloonMarker.swift
ChartsDemo-macOS/ChartsDemo-macOS/Demos/PieDemoViewController.swift
Source/Charts/Animation/Animator.swift
Source/Charts/Charts/BarLineChartViewBase.swift
Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Charts/PieChartView.swift
Source/Charts/Charts/PieRadarChartViewBase.swift
Source/Charts/Components/Legend.swift
Source/Charts/Components/YAxis.swift
Source/Charts/Jobs/AnimatedViewPortJob.swift
Source/Charts/Renderers/BarChartRenderer.swift
Source/Charts/Renderers/BubbleChartRenderer.swift
Source/Charts/Renderers/CandleStickChartRenderer.swift
Source/Charts/Renderers/HorizontalBarChartRenderer.swift
Source/Charts/Renderers/LegendRenderer.swift
Source/Charts/Renderers/LineChartRenderer.swift
Source/Charts/Renderers/PieChartRenderer.swift
Source/Charts/Renderers/RadarChartRenderer.swift
Source/Charts/Renderers/ScatterChartRenderer.swift
Source/Charts/Renderers/XAxisRenderer.swift
Source/Charts/Renderers/XAxisRendererHorizontalBarChart.swift
Source/Charts/Renderers/XAxisRendererRadarChart.swift
Source/Charts/Renderers/YAxisRenderer.swift
Source/Charts/Renderers/YAxisRendererHorizontalBarChart.swift
Source/Charts/Renderers/YAxisRendererRadarChart.swift
Source/Charts/Utils/ChartUtils.swift
Source/Charts/Utils/Platform.swift

Apple renamed keys and functions in Swift 4.2
Get a branch started to use these changes during the beta period.
Please merge into a new branch Swift-4.2

Changes for Swift 4.2, Xcode 10 and iOS 12

---

Source/Charts/Utils/Platform+Accessibility.swift

#3671
#3649
No memory leak.
* Added weak modifier to NSUIAccessibilityElement#container.
* Added guard statements.
I tested in example demo and my project.

Fix memory leak after rendering

---

Source/Charts/Components/AxisBase.swift

https://github.com/danielgindi/Charts/issues/3656
Ensure that the max number of labels in the Y Axis is correct.
I'm just changing the wrong assignment.
I didn't added any tests, but if necessary please let me know

Fix wrong assignment to axisMaxLabels property

---

Source/Charts/Data/Implementations/ChartBaseDataSet.swift
Source/Charts/Data/Implementations/Standard/BarChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/BarChartDataSet.swift
Source/Charts/Data/Implementations/Standard/BarLineScatterCandleBubbleChartDataSet.swift
Source/Charts/Data/Implementations/Standard/BubbleChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/BubbleChartDataSet.swift
Source/Charts/Data/Implementations/Standard/CandleChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ChartDataSet.swift
Source/Charts/Data/Implementations/Standard/LineChartDataSet.swift
Source/Charts/Data/Implementations/Standard/LineRadarChartDataSet.swift
Source/Charts/Data/Implementations/Standard/LineScatterCandleRadarChartDataSet.swift
Source/Charts/Data/Implementations/Standard/PieChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/PieChartDataSet.swift
Source/Charts/Data/Implementations/Standard/RadarChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ScatterChartDataSet.swift

#3578 
* Add missing properties to copy(with:) methods
Add any missing property to copy(with:) methods
I didn't add any tests cases, but if you think it will be valuable let me know.
#hacktoberfest #coinpaprika

Add missing properties to copy(with:) methods

---

Source/Charts/Charts/HorizontalBarChartView.swift

Horizontal Bar Chart legend issue #3301
This PR fixes the legend offset issue in case of horizontal bar charts.
The guard conditions in the method `calculateLegendOffsets` in the file `HorizontalBarChartView.swift` were wrong.
Tested in own app.

Fix legend offset bug for horizontal bar chart (Fixes #3301)

---

Source/Charts/Charts/BarLineChartViewBase.swift

chartScaled() func from ChartViewDelegate should be called after performing double tap
I use chartScaled() func from ChartViewDelegate and found that it doesn't called after performing double tap. I see explanation before chartScaled() which says that it callbacks when the chart is scaled / zoomed via pinch zoom gesture, but zoom() func is called after double tap in BarLineChartViewBase, so I think it's logical to add this functionality. If you don't like this solution then maybe other possible way is to add chartZoomed() or chartDoubleTapped() to ChartViewDelegate

add chartScaled() call after double tap in BarLineChartViewBase

---

Source/Charts/Renderers/LineChartRenderer.swift

This turns the gradient components and locations into constants and keeps their initialization with their declarations

Turned gradient components and locations into constants

---

Source/Charts/Charts/BarLineChartViewBase.swift

#3803 
eliminate not needed `chartTranslated` delegate method calls
Removed check if delegate is not nil because it's already done in next line by `?` operator
Added check that transformation matrix has really been changed before `chartTranslated` call

Fix condition that is checked before `chartTranslated` delegate method call

---

Source/Charts/Charts/BarLineChartViewBase.swift
Source/Charts/Charts/ChartViewBase.swift

Over the years, every I have come to implement this library, i have found that 1 feature for me has always been missing which is the ability to know when the user stopped panning across a chart to display values on the fly, and have it reset once the user lets go. I've yet to find a clean solution other than modifying the library, and I have added some callback logic to the ChartViewDelegate
To be able to install this from the master repo, and not always have to fork it to add this exact feature./
Added and optional method to the  ChartViewDelegate to tell the delegate that the pan gesture has reached a cancelled / ended state
```
public protocol ChartViewDelegate
{
...
/// Called when a user stop highlighting values while panning
@objc optional func chartViewDidEndPanning(_ chartView: …
```

Feature - ChartView Pan Ended Delegate Call

---

Source/Charts/Data/Implementations/Standard/ChartDataSet.swift

Allow more familiar API for collection types, the ability to implement more generic algorithms and simplify many existing algorithms by taking advantage of Collection conformances.
ChartDataSet adopts conformances:
MutableCollection
RandomAccessCollection
RangeReplaceableCollection

Add Collection conformances to ChartDataSet types

---

Source/Charts/Renderers/LineChartRenderer.swift

https://github.com/danielgindi/Charts/issues/2180
This fixes the sharpness to some of the connected data points for the line charts.
When a line is drawn, vertices need to be extended to account for sharp angles, to avoid the long vertices the app needs to draw each line 1 at a time (the way it already does for line charts with more than 1 color for their lines).
**Note that existing users may have to update their line cap type to rounded** because when each line is drawn 1 at a time there can be very small open space between connected lines (this already exists for line charts with more than 1 color)
**-----Before-----**
**-----After-----**

Fixes sharp edges on the line chart

---

Source/Charts/Data/Implementations/Standard/PieChartDataSet.swift
Source/Charts/Data/Interfaces/IPieChartDataSet.swift
Source/Charts/Renderers/PieChartRenderer.swift

This change adds a flag matchValueLineColorToPieSlice to PieChartDataSet and IPieChartDataSet protocol.
When enabled, valuelines will have the same color as slices they attached to.
matchValueLineColorToPieSlice is set to false by default, so colors won't be changed in old projects that use Charts.
https://github.com/danielgindi/Charts/issues/3480
To be able to draw valueLines with the same color as slices they come from. 
A bool flag gives an option to use the same color for all valueLines or different colors matching a corresponding pie slice color. 
Tested using sample project. 
```
set.matchValueLineColorToPieSlice = true
```

Multiple colors for valueline (Fixes #3480)

---

ChartsDemo-iOS/Objective-C/Components/BalloonMarker.swift
ChartsDemo-iOS/Swift/Components/BalloonMarker.swift
ChartsDemo-macOS/ChartsDemo-macOS/Demos/BarDemoViewController.swift
Source/Charts/Utils/Platform.swift

This is in line with how Objc interfaces are now imported

Replace AnyObject with Any

---

Source/Charts/Charts/PieRadarChartViewBase.swift

Leveraging the Swift stdlib to implement calculations around the `PieRadarChartViewBase.velocitySamples`

Velocity samples calculation

---

Source/Charts/Renderers/BarLineScatterCandleBubbleRenderer.swift

Use a stock iterator instead of a custom one.
A fix for https://github.com/danielgindi/Charts/issues/3848
The first circle was not being drawn by the BarLineScatterCandleBubbleRenderer.
Example:
The previous iterator was skipping the first version. There is another PR (
https://github.com/danielgindi/Charts/pull/3865) out that I felt didn't address the situation in the best way possible.
Fixed:

Use a stock iterator instead of a custom one.

---

Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Charts/PieChartView.swift
Source/Charts/Charts/RadarChartView.swift
Source/Charts/Components/AxisBase.swift
Source/Charts/Data/Implementations/ChartBaseDataSet.swift
Source/Charts/Data/Implementations/Standard/ChartData.swift
Source/Charts/Data/Implementations/Standard/CombinedChartData.swift
Source/Charts/Data/Implementations/Standard/PieChartData.swift
Source/Charts/Data/Implementations/Standard/ScatterChartData.swift
Source/Charts/Filters/DataApproximator.swift
Source/Charts/Highlight/BarHighlighter.swift
Source/Charts/Highlight/ChartHighlighter.swift
Source/Charts/Highlight/HorizontalBarHighlighter.swift
Source/Charts/Renderers/CandleStickChartRenderer.swift
Source/Charts/Renderers/CombinedChartRenderer.swift
Source/Charts/Renderers/PieChartRenderer.swift
Source/Charts/Renderers/RadarChartRenderer.swift
Source/Charts/Renderers/YAxisRenderer.swift
Source/Charts/Utils/Transformer.swift

Inspired by WWDC'18 Embracing Algorithms
Charts relies heavily on custom algorithm implementations. Many of these are common algorithms and should instead rely on the built in implementations. In this PR I have updated the obvious candidates.
I have intentionally omitted the longer algorithms as some A) are unique algorithms and B) can become much simpler with some additional changes in the framework (i.e. Collection conformances introduced in 4.0.0).

Migrating to built-in algorithms

---

Source/Charts/Charts/ChartViewBase.swift

Create a callback to get when ChartView stops animating
Create another function in `ChartViewDelegate` protocol and calls in `animatorStopped` callback from `Animator`

Create `chartViewDidEndAnimate` in ChartViewDelegate

---

Source/Charts/Renderers/HorizontalBarChartRenderer.swift

https://github.com/danielgindi/Charts/issues/3850
Improve HorizontalBarChart offset calculation for negative value labels.
Just subtract the bar width from negative offset calculation. 
Tested with positive and negative value set, value icons, drawValueAboveBarEnabled (true/false)

HorizontalBarChar value label offset calculation 

---

Source/Charts/Data/Implementations/Standard/BarChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/BubbleChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/CandleChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ChartDataEntryBase.swift
Source/Charts/Data/Implementations/Standard/PieChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/RadarChartDataEntry.swift

The only data required to initialize an entry is an x and y value (or y in the case of Pie and Radar). All other data can easily be updated by initializing and assigning properties on the entry. Therefor, those initializers should be the ones marked as convenience. This also has the side effect of faster data set creation when only providing required data as those initializers no longer chain through to designated initializers.
Made initializer declarations consistent.

Reassess convenience initializers

---

Source/Charts/Data/Implementations/Standard/BarChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/BubbleChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/CandleChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ChartDataEntryBase.swift
Source/Charts/Data/Implementations/Standard/PieChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/RadarChartDataEntry.swift
Tests/Charts/EquatableTests.swift

There is no need to restrict `ChartEntry.data` to `AnyObject`. This PR loosens that restriction. As a result we cannot compare `data`, though this should never have been the case in the first place.

Data as any

---

Source/Charts/Renderers/PieChartRenderer.swift
Source/Supporting Files/Info.plist

https://github.com/danielgindi/Charts/issues/4001
This code change helps safeguard against hard crashes caused by an array operation.  It doesn't fix potential issues that could cause such a condition in the first place.
I manually stepped through the attached demo project and verified the PieChart views looked and behaved as expected.

Added a safety check before an unsafe array operation

---

Source/Charts/Renderers/BarChartRenderer.swift

https://github.com/danielgindi/Charts/issues/3659
Fixing the issue, see link above.
Preventing the stacked bar chart from crashing when there was different number of stacks in columns.
No test added, but i did test this against other chart views and confirmed that this fix did not make an affect on them.

fixed stacked chart bug when there are different stacks on columns.

---

Source/Charts/Renderers/LineChartRenderer.swift

Fix issue #1626 
The `Highlight` object generated in the `ChartViewBase` class contains a `Double.NaN` y-value when calling the `highlightValue` functions that does not require a y-value.
In the `LineChartRenderer` class, the `drawHighlighted` function passes the NaN y-value into the `Transformer` `pixelForValues` to apply the `valueToPixelMatrix`, which will result in the x-value being a NaN; therefore, causing the `LineScatterCandleRadarRenderer` `drawHighlightLines` to move to a CGPoint with a NaN x-value.
To fix this, the y-value being passed into `pixelForValues` should be from the `entryForXValue`.

Avoid passing NaN to CoreGraphics API (Fixes #1626)

---

Source/Charts/Renderers/BarLineScatterCandleBubbleRenderer.swift
Source/Charts/Renderers/LineChartRenderer.swift

1. change XBounds iterator to use self.min + self.range rather than self.x
2. align drawLinear,  drawCubicBezier to new XBounds iterator.
3. fix unexpected dash line during linear animation due to reading the next entry point
#4093, #3960
It seems to fix issue 3, the simple way is to call `for j in _xBounds.dropLast()` instead of `for j in _xBounds` so it ignores the last point, then j+1 will always be the last point to avoid additional dash line

Fix line chart x axis animation #4093, also close #3960

---

Source/Charts/Renderers/YAxisRenderer.swift

MPAndroidChart library allows overriding of this method in a subclass of YAxisRenderer. This PR changes the access modifier so it can be overridden in iOS as well.

Allowing overriding for YAxisRenderer.drawYLabels

---

Source/Charts/Utils/Platform+Color.swift
Source/Charts/Utils/Platform+Gestures.swift
Source/Charts/Utils/Platform+Graphics.swift
Source/Charts/Utils/Platform+Touch Handling.swift

https://github.com/danielgindi/Charts/issues/4233
Fixes compatibility with Catalyst
Essentially, in the "Platform+" files, attempts to alias types to their AppKit equivalents for regular macOS apps works file, but fails in Catalyst apps because while those are Mac apps, Catalyst needs UIKit for certain things. 
Basically I changed this line in four files
`#if canImport(AppKit)`
to 
`#if canImport(AppKit) && !targetEnvironment(macCatalyst)`
Which causes the macro to skip over this on Catalyst apps. 
No changes to unit testing performed, though I have successfully tried my fork in a Catalyst app, and the changes above have no effect on the macOS demo app in the project.

Changes to fix Catalyst compatibility

---

Source/Charts/Renderers/LineChartRenderer.swift

This obviously does not consider slope that's outside,
But these cases will be clipping by CoreGraphics anyway.
Doing a full line collision test here is an overkill.
Fixes a performance degradation introduced here: https://github.com/danielgindi/Charts/pull/4100
It was a big chunk of code that was introduced to fix a subtle bug, but most of the fix was actually the code calling it - figuring out the first/last line coordinate for stepped lined.
Revert to almost-the-previous-implementation, keeping the actual fix in place.
When testing simply that `lastCoordinate.x > left && firstCoordinate.x < right`, it's enough to ensure the line is horizontally somewhere in the content rect.
The equivalent vertical check was inverted, causing rare issues.
But the main issue was actually with stepped …

Use faster check for line whether it's inside drawing rect

---

Source/Charts/Charts/RadarChartView.swift
Source/Charts/Components/YAxis.swift
Source/Charts/Renderers/YAxisRenderer.swift
Source/Charts/Renderers/YAxisRendererHorizontalBarChart.swift
Source/Charts/Renderers/YAxisRendererRadarChart.swift

+ also consider other renderers
Fixes https://github.com/danielgindi/Charts/pull/3406
https://github.com/danielgindi/Charts/pull/3406
Extend the solution to not be a piece of dead code.
Considering the new property in all `YAxisRenderer`s, while correctly setting the default of `10` only to Radar charts.
Visually, + CI.

labelXOffset = 10 is default for radar chart only

---

Source/Charts/Charts/BarLineChartViewBase.swift

Straighten the semantics of the event.
Currently the relatively new protocol method is called in the end of the gesture, even if the gesture does not mean "pan". This could cause unexpected bugs.

Call chartViewDidEndPanning on when *panning* is ended

---

ChartDataTests.swift
Charts.xcodeproj/project.pbxproj
Source/Charts/Data/Implementations/Standard/ChartData.swift

Fixes an issue with string comparison in ChartData for finding a dataset by its label (Fixes #4274)
ChartData::getDataSetByLabel has a bug where the string comparison is checking the same string against itself due to the functions parameter having the same name as a variable within the closures scope. This change renames the variable to fix the issue.
#4274 
- Fixes the bug
- Adds some unit tests to prevent the relevant issue from regressing
- No major changes here, just a quick fix
- Added some tests that check case sensitivity
- Added some tests that ignore case
- Added some tests that check for the expected nil case

Fix for #4274 string comparison issue in ChartData::getDataSetByLabel

---

Source/Charts/Charts/PieRadarChartViewBase.swift

https://github.com/danielgindi/Charts/pull/3883
The sampling algorithm was butchered, so much that old samples do not get dropped (only one of them gets dropped).
The issue is presented when dragging the chart for more than a second, and the releasing. The velocity is incorrect.
Restored older algorithm.

Restored correct velocity sampler

---

Source/Charts/Data/Implementations/ChartBaseDataSet.swift

Reduces the type-checking time of a `debugDescription` variable by at least an order of magnitude.
Because type inference with `+` and literals has to do a lot of overload checking (for every `ExpressibleBy____Literal`), many expressions which use `+` for string concatenation with literals in contexts where type information is sparse may inadvertently cause a type checker performance explosion. In this case, we are concatenating an anonymous closure argument with a string literal, which caused a compilation time on the order of multiple seconds (on my MBP, YMMV). With this change, the type checking of this expression completes in under 100ms.
There's no behavior change here. We could consider adding `-Xfrontend -warn-long-expression-type-checking=<limit>` to the Xcode project to catch …

Use interpolation instead of '+' concatenation for problematic expression

---

Source/Charts/Charts/PieChartView.swift
Source/Charts/Utils/Platform+Graphics.swift
Source/Charts/Utils/Platform.swift

address #4033. when it's half pie and width is larger than height, draw bigger pie chart. 
I‘m not in a hurry to merge before it's fully tested and reviewed.
The key idea is to fake the radius and adjust the circle box.
when screen width <= height, it should be the same as a full pie chart, since the radius should be diameter/2 anyway;
but when screen width > height, the radius is min(width, height) to use the maximum space
before:
after:
the portrait portion (width < height) should not be affected.

address #4033 draw half pie chart more accurate

---

Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Renderers/PieChartRenderer.swift
Source/Charts/Renderers/XAxisRendererHorizontalBarChart.swift
Source/Charts/Renderers/YAxisRenderer.swift
Source/Charts/Renderers/YAxisRendererHorizontalBarChart.swift
Source/Charts/Utils/Platform.swift

Fix warnings for vars;
Fix unused instants;
Remove a duplicated function NSUIMainScreen()

Fix warnings on current code base

---

Source/Charts/Components/AxisBase.swift

Fixes issue where if you overrode the
formatter it didn't matter because a new one would
just replace it.

Fix AxisBase Formatter Getter (Fixes #4365)

---

Package.swift

Fixes Xcode 12 beta warning: `The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.`

Increase iOS version to 9 in Package.swift

---

Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Charts/CombinedChartView.swift
Source/Charts/Charts/PieRadarChartViewBase.swift
Source/Charts/Components/AxisBase.swift
Source/Charts/Components/Legend.swift
Source/Charts/Data/Implementations/Standard/BarChartDataEntry.swift
Source/Charts/Data/Implementations/Standard/ChartData.swift
Source/Charts/Data/Implementations/Standard/CombinedChartData.swift
Source/Charts/Data/Implementations/Standard/PieChartData.swift
Source/Charts/Filters/DataApproximator+N.swift
Source/Charts/Filters/DataApproximator.swift
Source/Charts/Formatters/IndexAxisValueFormatter.swift
Source/Charts/Highlight/BarHighlighter.swift
Source/Charts/Highlight/ChartHighlighter.swift
Source/Charts/Highlight/CombinedHighlighter.swift
Source/Charts/Highlight/HorizontalBarHighlighter.swift
Source/Charts/Renderers/BarChartRenderer.swift
Source/Charts/Renderers/BubbleChartRenderer.swift
Source/Charts/Renderers/CandleStickChartRenderer.swift
Source/Charts/Renderers/CombinedChartRenderer.swift
Source/Charts/Renderers/DataRenderer.swift
Source/Charts/Renderers/HorizontalBarChartRenderer.swift
Source/Charts/Renderers/LegendRenderer.swift
Source/Charts/Renderers/LineChartRenderer.swift
Source/Charts/Renderers/PieChartRenderer.swift
Source/Charts/Utils/ChartColorTemplates.swift

`count` is frequently used on collections to infer other semantic meaning. These uses have been replaced with the correct version.

Remove misuse of `count`

---

Package.swift

We need [dynamic linking](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md#methods-2) for this dependence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielgindi/charts/4478)

Alternative for SPM dynamic linking

---

Source/Charts/Data/Implementations/Standard/BarChartDataSet.swift

Remove unnecessary ternary expression in boolean return statement.

Remove unnecessary ternary in boolean expression

---

Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Charts/PieChartView.swift
Source/Charts/Data/Implementations/Standard/ChartDataSet.swift
Source/Charts/Data/Implementations/Standard/CombinedChartData.swift
Source/Charts/Highlight/PieHighlighter.swift
Source/Charts/Renderers/BarChartRenderer.swift
Source/Charts/Renderers/BubbleChartRenderer.swift
Source/Charts/Renderers/CandleStickChartRenderer.swift
Source/Charts/Renderers/DataRenderer.swift
Source/Charts/Renderers/HorizontalBarChartRenderer.swift
Source/Charts/Renderers/LineChartRenderer.swift
Source/Charts/Renderers/PieChartRenderer.swift
Source/Charts/Renderers/RadarChartRenderer.swift
Source/Charts/Renderers/ScatterChartRenderer.swift

New Collection API is encouraged for access to data sets in ChartData. DataSets is only exposed for custom chart use cases (like PieChartData). We should not be relying on it internally. There are a couple oddities that (have always) exist like down casting elements to a specific type. Those won't be resolved until objc support is either removed, or refactored out of the main chart data types.

Remove internal use of datasets

---

Source/Charts/Data/Implementations/ChartBaseDataSet.swift

FIx copy-paste error in the copying constructor
Replace duplicated line (drawValuesEnabled) by drawIconsEnabled
No tests required.

ChartBaseDataSet, copy constructor - missing drawIconsEnabled parameter initialization

---

Source/Charts/Charts/ChartViewBase.swift

1. Remove extra private store value.
2. Use `min` and `max`

ChartViewBase cleanup

---

Charts.xcodeproj/project.pbxproj
Charts.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Source/Charts/Data/Implementations/Standard/ChartDataSet.swift
Source/Charts/Highlight/ChartHighlighter.swift
Source/Charts/Highlight/CombinedHighlighter.swift
Source/Charts/Highlight/RadarHighlighter.swift
Source/Charts/Renderers/YAxisRendererRadarChart.swift

Provides convenient algorithms written by the community, curated be the swift core team.

Import swift algorithms

---

Source/Charts/Data/Implementations/Standard/ChartDataSet.swift

#4571 
Incorrectly returned index beyond the last valid index. This is now corrected

Fix bounds checks on binary search

---

Source/Charts/Renderers/YAxisRenderer.swift

Fixed incorrect guard return statement when rendering limit lines

---

README.md

Added a link to a video showing how to add the Charts framework (specifically a Bar Chart) to a SwiftUI project

Add Tutorial Link.md

---

.github/workflows/swift.yml
Charts.podspec
Charts.xcodeproj/project.pbxproj
Charts.xcodeproj/xcshareddata/xcschemes/Charts.xcscheme
Charts.xcodeproj/xcshareddata/xcschemes/ChartsTests.xcscheme
Charts.xcworkspace/xcshareddata/swiftpm/Package.resolved
ChartsDemo-iOS/ChartsDemo-iOS.xcodeproj/project.pbxproj
Package.swift
Source/Charts/Components/Marker.swift
Source/Charts/Formatters/AxisValueFormatter.swift
Source/Charts/Formatters/ValueFormatter.swift
Source/Charts/Highlight/Highlighter.swift
Source/Charts/Renderers/Scatter/ShapeRenderer.swift

Fixes all issues related to not having cocoapods for version 4.X
https://github.com/danielgindi/Charts/issues/4776
https://github.com/danielgindi/Charts/issues/4740
https://github.com/danielgindi/Charts/issues/4611
https://github.com/danielgindi/Charts/issues/4582
https://github.com/danielgindi/Charts/issues/4572
https://github.com/danielgindi/Charts/issues/4448
https://github.com/danielgindi/Charts/issues/4541
Update project settings and podspec to be able to publish a 4.0 pod to cocoapods
- Update the project settings to target a higher version since `SwiftAlgorithms` support only from iOS 10, macOS 10.12, tvOS 10 (https://github.com/jshier/swift-pods/blob/main/SwiftAlgorithms.podspec)
- Fix warnings with update from protocols being constrained by `class`
- Validate that the build/tests …

Update project settings to support publishing pod

---

README.md

Cocoadocs does not exist anymore.
So I suggest remove the link from the README which could mislead a beginner.

Remove Cocoadocs reference from README

---

ChartsDemo-iOS/Objective-C/AppDelegate.m
ChartsDemo-iOS/Swift/AppDelegate.swift

Issue: iOS demo project navigation bar transparent 
Objc:
Swift:
| Before Fix    | After Fix |
| ----------- | ----------- |
|   ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-07-27 at 13 41 59](https://user-images.githubusercontent.com/15813435/181170839-474afaec-112f-4cd6-93df-d4d85992bc28.png)    | ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-07-27 at 13 41 30](https://user-images.githubusercontent.com/15813435/181170860-49a0d4de-7009-466d-ba7d-caa0397823fc.png)       |

Fix navigation bar transparent issue

---

.gitignore
Package.resolved
Source/Charts/Data/Implementations/Standard/ChartDataSet.swift
Source/Charts/Utils/ChartUtils.swift

I'm currently experimenting with the latest development Swift 5.7 toolchain and the Charts library was not compiling due to a bug in the implementation of `RangeReplaceableCollection` on `ChartDataItem`.
This PR fixes that by adding the missing protocol method and also fixes a couple of compiler warnings (which I think also exist on the latest stable toolchain).
More info on this here: https://github.com/apple/swift/issues/58737 - the reason this compiled pre-5.7 was due to a bug in Swift which was due to be fixed in 5.6, reverted and will ship in 5.7 by the looks of it.
Library can now be compiled with Swift 5.7.
Library continues to compile under 5.6.
I wasn't able to get the snapshots to pass on my M1 Max laptop - maybe I'm using the wrong simulator. The failures were very subtle and I …

Fixes for Swift 5.7 compiler

---

Source/Charts/Animation/ChartAnimationEasing.swift

https://github.com/danielgindi/Charts/issues/4835
in Xcode14 there is an compiler check error because of ambiguity of some math arithmetics, so this pr aim to fix it  
Because of this compiler error, i aim to fix this problem for xcode14-beta versions
There are no architectural changes, I just put Double casting into magic number as `1.0`

Add double mark for compiler check related with issue #4835

---

Source/Charts/Data/Implementations/Standard/ChartDataSet.swift

there will be no warning in demo project
As I noticed in the demo project, it was giving a warning that the addEntryOrdered(_ e: ChartDataEntry) function is not used. That's why I made the development

fixed no used warning

---

.github/workflows/swift.yml

The GitHub checkout action v2 uses Node.js 12. This version of Node is deprecated and will be fully removed in summer 2023, see [this blog post](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
I have updated all checkout actions to us v3 instead of v2.
I couldn't test it with this repo, but I have not experienced any issues with the other workflows where I have done the upgrade.
_Edit_: CI is not failing and the warnings are gone: https://github.com/danielgindi/Charts/actions/runs/4658235640

Fix Node 12 deprecation warning

---

Source/Charts/Charts/ChartViewBase.swift
Source/Charts/Components/AxisBase.swift
Source/Charts/Components/ChartLimitLine.swift
Source/Charts/Components/Legend.swift
Source/Charts/Data/Implementations/Standard/BarChartDataSet.swift

Xcode 14.3 produces some missing import warnings:
I have added all the necessary imports to resolve the warnings.
I have build the project with Xcode 14.2 and 14.3 for macOS and iOS.

Fix Xcode 14.3 import warnings

---

Source/Charts/Renderers/PieChartRenderer.swift

* Remove excess code around pie slice spacing, reuse the code that actually works for uniform spacing

Improved uniform spacing in pie charts

---

Source/Charts/Renderers/LineChartRenderer.swift

When updating the data set for the chart and then animating it, sometimes highlights are generated for the
// removed sets. This guard prevents OOB in the case where the new set has less data than the old set
Fix crash when updating datasets and animating

Fix crash in LineChartRenderer.swift when animating data set changes

---

Source/Charts/Utils/ChartUtils.swift

Resolved log10 and pow errors by explicitly calling Double.log10() and Double.pow(). Fixed type mismatch in division operation (shifted / magnitude). Ensured compatibility with latest Swift compiler requirements. Preparing to apply these fixes to the main library as well.
Fix Swift 5.9+ compatibility issues related to log10 and pow usage.
Ensure the library builds successfully on Xcode 16 and remains backward compatible.
Replaced instance method calls on Double (log10, pow) with Foundation equivalents:
Before: log10(self < 0 ? -self : self)
After: Foundation.log10(abs(self))
Before: pow(10.0, Double(pw))
After: Foundation.pow(10.0, Double(pw))
Ensured compatibility with Swift 5.9+ by explicitly calling Foundation methods.
Updated code to ensure correct return types (e.g., Double instead …

Fix FloatingPoint functions: Replace instance calls with static Double

---

Source/Charts/Data/Implementations/Standard/ChartData.swift
Source/Charts/Data/Implementations/Standard/RadarChartData.swift
Source/Charts/Renderers/BarChartRenderer.swift
Source/Charts/Renderers/BubbleChartRenderer.swift
Source/Charts/Renderers/CandleStickChartRenderer.swift
Source/Charts/Renderers/LineChartRenderer.swift
Source/Charts/Renderers/PieChartRenderer.swift
Source/Charts/Renderers/RadarChartRenderer.swift
Source/Charts/Renderers/ScatterChartRenderer.swift

[Crash Issue](https://github.com/danielgindi/Charts/issues/4960
)
- We face a crash when we attempt to highlight the values for the combined chart.
- Added safe subscript logic.
- Add this code snippet to demo project's CombinedChartViewController class.
```
func selectHighLights() {
var highlight: [Highlight] = []
chartView.data?.dataSets.enumerated().forEach { index, dataSet in
dataSet.entriesForXValue(0.5).forEach { entry in
highlight.append(Highlight(x: entry.x, y: entry.y, dataSetIndex: index))
}
}
chartView?.highlightValues(highlight)
}
override func viewDidAppear(_ animated: Bool) {
super.viewDidAppear(animated)
DispatchQueue.main.asyncAfter(deadline: .now() + 2.0, execute: {
self.selectHighLights()
})
}
```

Added Safe index subscript logic for ChartData

---

Source/Charts/Data/Implementations/Standard/BarChartDataSet.swift
Source/Charts/Data/Interfaces/BarChartDataSetProtocol.swift
Source/Charts/Renderers/BarChartRenderer.swift
Source/Charts/Renderers/HorizontalBarChartRenderer.swift

Many years people needs to fork this repo to implement rounded bars in bar chart.
In pull requests exists also fixing same issue, but my implementation is more configurable
1) You can add corner radius for specific corners only (for example only for topLeft + topRight corner)
2) Corner radius works also for highlight when select bars 
How to use:
```
var dataSet = BarChartDataSet(entries: yVals)
dataSet.cornerRadius = 6
dataSet.roundedCorners = .allCorners
// or
dataSet.roundedCorners = [.topLeft, .topRight]
```

Posibility to add Corner Radius for rounded bars in bar chart
