Charts/Charts.xcodeproj/project.pbxproj, Charts/Classes/Charts/BubbleChartView.swift, Charts/Classes/Data/BubbleChartData.swift, Charts/Classes/Data/BubbleChartDataEntry.swift, Charts/Classes/Data/BubbleChartDataSet.swift, Charts/Classes/Renderers/BubbleChartRenderer.swift, Charts/Classes/Utils/ChartTransformer.swift, ChartsDemo/ChartsDemo.xcodeproj/project.pbxproj, ChartsDemo/Classes/DemoListViewController.m, ChartsDemo/Classes/Demos/BubbleChartViewController.h, ChartsDemo/Classes/Demos/BubbleChartViewController.m, ChartsDemo/Classes/Demos/BubbleChartViewController.xib
Moved from https://github.com/danielgindi/ios-charts/pull/25 to a separate branch
=> Bubble chart work by @petester42

Charts/Classes/Charts/BarLineChartViewBase.swift
To manually set the grid size of a LineChart.
=> Added possibility to set the axisLabelModulus manually.

Charts/Classes/Charts/BubbleChartView.swift
add missing module CoreGraphics for BubbleChartView
=> add missing module CoreGraphics for BubbleChartView

Charts/Classes/Charts/ChartViewBase.swift
I think it's a typo, right? :)
=> optional protocol method should not be force unwrapped

Charts/Classes/Charts/BarLineChartViewBase.swift, Charts/Classes/Charts/ChartViewBase.swift, Charts/Classes/Charts/PieChartView.swift, Charts/Classes/Charts/PieRadarChartViewBase.swift, Charts/Classes/Charts/RadarChartView.swift, Charts/Classes/Data/ChartDataSet.swift
This fixes some compiler errors in beta 3. Oops. Deleted my remote while trying to fix the history.
=> Fixes for beta 3

Charts.podspec
Fixed the pod spec so the version does not have to be specified twice
=> Updated podspec

Charts.podspec
fixes #289. I've already pushed to cocoapods.
=> bump podspec to 2.1.3

Charts/Classes/Components/ChartLimitLine.swift, Charts/Classes/Renderers/ChartXAxisRenderer.swift, Charts/Classes/Renderers/ChartXAxisRendererHorizontalBarChart.swift, Charts/Classes/Renderers/ChartYAxisRenderer.swift, Charts/Classes/Renderers/ChartYAxisRendererHorizontalBarChart.swift, ChartsDemo/Classes/Demos/LineChart1ViewController.m
Added new enums for ChartLimitLabelPosition for a more flexible label positioning.
- LeftTop
- LeftBottom
- RightTop
- RightBottom
=> Enhanced label positioning at limit lines (enum ChartLimitLabelPosition)

Charts/Classes/Renderers/CombinedChartRenderer.swift
As discussed in https://github.com/danielgindi/ios-charts/issues/446
=> Changed _chart access modifier from private to internal

Charts/Classes/Renderers/ChartXAxisRendererBarChart.swift
Reverts danielgindi/ios-charts#489
=> Revert "BUGFIX:fix xAxis labels of bar chart"

Charts/Classes/Data/ChartData.swift
seems we forgot to initialize dataSets in setter?
=> add initialize dataSets in setter

Charts.podspec, Gemfile, Gemfile.lock, README.md
- changes podspec format to include the realm subspec
- adds cocoapods to gemfile
- updates readme to include realm pod spec
closes #723
=> Update podspec for realm and 2.2.0

Charts/Classes/Components/ChartAxisBase.swift, Charts/Classes/Renderers/ChartXAxisRenderer.swift, Charts/Classes/Renderers/ChartXAxisRendererBarChart.swift, Charts/Classes/Renderers/ChartXAxisRendererHorizontalBarChart.swift, Charts/Classes/Renderers/ChartYAxisRenderer.swift, Charts/Classes/Renderers/ChartYAxisRendererHorizontalBarChart.swift, ChartsDemo/Classes/Demos/LineChart1ViewController.m
add an option to set line cap of axis grid line
=> add an option to set line cap of axis grid line

README.md
remove duplicated statement according to #888
=> remove duplicated statement

Charts/Classes/Data/Implementations/Standard/BarChartDataSet.swift, Charts/Classes/Data/Interfaces/IBarChartDataSet.swift, Charts/Classes/Renderers/BarChartRenderer.swift, Charts/Classes/Renderers/HorizontalBarChartRenderer.swift, ChartsDemo/Classes/DemoBaseViewController.h, ChartsDemo/Classes/DemoBaseViewController.m, ChartsDemo/Classes/Demos/AnotherBarChartViewController.m, ChartsDemo/Classes/Demos/BarChartViewController.m, ChartsDemo/Classes/Demos/CombinedChartViewController.m, ChartsDemo/Classes/Demos/HorizontalBarChartViewController.m, ChartsDemo/Classes/Demos/MultipleBarChartViewController.m, ChartsDemo/Classes/Demos/NegativeStackedBarChartViewController.m, ChartsDemo/Classes/Demos/PositiveNegativeBarChartViewController.m, ChartsDemo/Classes/Demos/StackedBarChartViewController.m, ChartsRealm/Classes/Data/RealmBarDataSet.swift
Based on my feature request (see #822).
With these changes, the border color of bars could be set independently. Updates on example project helps understanding this feature.
=> Supporting borders on bars, Fixes issue #822

ChartsDemo/Classes/DemoBaseViewController.m
Fix #1014: fix combined chart crash while toggle bar borders.
=> Fix #1014: fix combined chart crash while toggle bar borders

Charts.podspec
=> fix Realm pod spec typo

Charts.podspec, Charts/Classes/Utils/ChartPlatform.swift
Xcode 8 beta 3 and 4 needed this to build.
=> Few more changes needed to build with Swift 2.3

ChartsDemo/Classes/DemoBaseViewController.m, ChartsDemo/Classes/Demos/CombinedChartViewController.m, ChartsDemo/Classes/Demos/CubicLineChartViewController.m, ChartsDemo/Classes/Demos/LineChart1ViewController.m, ChartsDemo/Classes/Demos/LineChart2ViewController.m, ChartsDemo/Classes/Demos/MultipleLinesChartViewController.m, ChartsDemo/Classes/Demos/PieChartViewController.m, ChartsDemo/Classes/Demos/PiePolylineChartViewController.m, ChartsDemo/Classes/Demos/RadarChartViewController.m
=> fix more ChartsDemo complains

Charts/Classes/Utils/ChartUtils.swift, ChartsRealm/Classes/Data/RealmBarDataSet.swift, ChartsRealm/Classes/Data/RealmBubbleDataSet.swift, ChartsRealm/Classes/Data/RealmLineDataSet.swift, ChartsRealm/Classes/Data/RealmLineRadarDataSet.swift, ChartsRealm/Classes/Data/RealmLineScatterCandleRadarDataSet.swift, ChartsRealm/Classes/Data/RealmScatterDataSet.swift
fix bridgedObjCGetStringArray warning and more copyWithZone(_ zone: NSZone?) -> AnyObject errors
=> fix bridgedObjCGetStringArray warning and more copyWithZone(_ zone: NSZone?) -> AnyObject errors

Charts.xcodeproj/project.pbxproj
https://github.com/danielgindi/Charts/issues/1462 change Charts baseSDK to iOS 10
=> change Charts baseSDK to iOS 10

Source/Charts/Charts/BarChartView.swift, Source/Charts/Charts/PieRadarChartViewBase.swift
=> porting #1452 into master

Source/Supporting Files/Info.plist
=> bump Charts version to 3.0.0

ChartsDemo/Classes/Demos/BarChartViewController.m
fix bar chart in demo that date starts at 0. It should be 1 or the first value will be 0.0
this address the first issue in #1639
=> fix bar chart in demo that date starts at 0

README.md
Updates README.md to reflect changes made to "Build Options" in Xcode 8.2+.
=> Update "Usage" section of README

Charts.xcodeproj/project.pbxproj
This pull request adds option to use in library extensions.
=> Add support for extensions

ChartsDemo/Classes/Demos/BubbleChartViewController.m
duplicated code for set1 in set2 section
=> duplicated code for set1 in set2 section

Source/Charts/Charts/ChartViewBase.swift
=> Added custom text alignment for noData

Source/Charts/Renderers/BubbleChartRenderer.swift
=> BubbleChart uses correct colour for index now.

Source/Charts/Data/Implementations/Standard/ChartDataSet.swift
This is for the inline bubble selection #2060
Have the ability to select multiple bubbles in the same index
Just take in consideration the less than or equal ```abs(closestYValue - yValue)```
Implementing in the my project test it in the demo also
=> Support inlune bubble viz selection

Source/Charts/Components/Legend.swift
should fix #3860. maxHeight didn't count the last label
=> fix #3860. maxHeight didn't count the last label

Charts.xcodeproj/project.pbxproj, Charts.xcodeproj/xcshareddata/xcschemes/Charts.xcscheme, Charts.xcodeproj/xcshareddata/xcschemes/ChartsTests.xcscheme, ChartsDemo-iOS/ChartsDemo-iOS.xcodeproj/project.pbxproj, ChartsDemo-macOS/ChartsDemo-macOS.xcodeproj/project.pbxproj
This PR updates the project to the recommended settings for Xcode 11 and Swift 5.1 including the recommended localization and internationalization changes.
=> Performed recommended localization and internationalization changes.

README.md
This PR adds a link to my tutorial about using Radar Charts.
In this tutorial I wrote a step-by-step guide about how to recreate the Radar Chart example from the readme.
=> Update README.md, added link to tutorial about Radar Charts.

README.md
Hi! I have created tutorial with simple project example. It should be useful for those who want to use charts with SwiftUI.
I added a link to my tutorial in 3rd party tutorials section below other tutorials
=> Update readme.md with link to SwiftUI tutorial

.github/workflows/swift.yml
Ensuring that the SPM target is properly configured
=> Added SPM build action

Source/Charts/Charts/BarLineChartViewBase.swift
https://github.com/danielgindi/Charts/issues/4442
Fix the regression
See the code
=> Revert https://github.com/danielgindi/Charts/pull/4271 and disable parent scroll view on dragging

README.md
Added 2 links to blog posts showing how to set up a basic bar chart and how to highlight selected value with a custom marker
=> Added tutorial links

Source/Charts/Components/ComponentBase.swift
=> Fix yOffset documentation typo

ChartsDemo-iOS/Swift/DemoBaseViewController.swift
=> Unnecessary space Removal and Semicolons are removed

README.md
Adding an interactive linear chart tutorial showing a fairly real-world feature implementation with UIKit.
=> Adding a tutorial link to README.md

.github/workflows/swift.yml, ChartsDemo-iOS/Swift/DemoBaseViewController.swift
=> Merge from master
